'use strict'

// Bun server emitter.
// Input:  Arc program with RouteDecl + ModelDecl + JobDecl nodes
// Output: A complete dist/server.js that runs with `bun dist/server.js`
//
// options.db: 'sqlite' (default) | 'postgres'
//
// Performance strategy:
//   - Routes compiled to a radix-trie decision tree at build time (zero regex at request time)
//   - SQL queries generated as constant strings (no query-builder overhead at runtime)
//   - Typed JSON serialization per response shape (no generic JSON.stringify overhead)
//   - Bun.serve() used directly (20% faster than fetch-handler style)

const { JsEmitter } = require('./js')
const { compileRoutes } = require('../compilers/route-compiler')
const { emitAuthPreamble } = require('./auth-helpers')
const { emitQueuePreamble, emitEmailPreamble, emitJobEnqueueWrapper } = require('./queue-helpers')
const { arcTypeToSql: _arcTypeToSql } = require('../compilers/sql-types')

const _SAFE_IDENT = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/

class BunServerEmitter {
  constructor(options = {}) {
    this.options = options
    this.db = options.db ?? 'sqlite'
    this.jsEmitter = new JsEmitter(options)
  }

  get isPg() { return this.db === 'postgres' }

  emitProgram(program) {
    const routes = program.declarations.filter(d => d.type === 'RouteDecl')
    const schemas = program.declarations.filter(d => d.type === 'ModelDecl')
    const jobs = program.declarations.filter(d => d.type === 'JobDecl')
    const hasAuth = routes.some(r => r.annotations?.includes('@auth'))

    if (routes.length === 0 && schemas.length === 0) return ''

    const parts = []

    parts.push(this.emitPreamble(schemas))
    if (hasAuth) parts.push(emitAuthPreamble(this.options.auth ?? {}))

    // Queue + email always emitted (tiny, zero deps)
    parts.push(emitQueuePreamble())
    parts.push(emitEmailPreamble())

    for (const schema of schemas) {
      parts.push(this.emitModelHelpers(schema))
    }

    for (const job of jobs) {
      parts.push(this.emitJobHandler(job))
      // Public enqueue wrapper: `const SendEmail = (...args) => Queue.enqueue(_job_SendEmail, ...args)`
      parts.push(emitJobEnqueueWrapper(job.name))
    }

    for (const route of routes) {
      parts.push(this.emitRouteHandler(route))
    }

    const routeSpecs = routes.map(r => ({
      method: r.method,
      path: r.path,
      handlerName: this.routeHandlerName(r),
    }))
    parts.push(compileRoutes(routeSpecs))

    parts.push(this.emitBunServe(routes, schemas))

    return parts.filter(Boolean).join('\n\n')
  }

  // ── Preamble ─────────────────────────────────────────────────────────────────

  emitPreamble(schemas) {
    const hasDb = schemas.length > 0
    const dbSetup = hasDb ? (this.isPg ? this._pgSetup() : this._sqliteSetup()) : ''

    return `
// Generated by Arc compiler — do not edit
'use strict'
${dbSetup}
// Response helpers
const _json = (data, status = 200, headers = {}) =>
  new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json', ...headers }
  })

const _html = (body, status = 200) =>
  new Response(body, { status, headers: { 'Content-Type': 'text/html; charset=utf-8' } })

const _text = (body, status = 200) =>
  new Response(body, { status, headers: { 'Content-Type': 'text/plain; charset=utf-8' } })

const _redirect = (location, status = 302) =>
  new Response(null, { status, headers: { Location: location } })

// Body parser: JSON or application/x-www-form-urlencoded
const _MAX_BODY_SIZE = 1024 * 1024 // 1 MB
async function _parseBody(req) {
  const length = +(req.headers.get('content-length') ?? 0)
  if (length > _MAX_BODY_SIZE) throw Object.assign(new Error('Request body too large'), { status: 413 })
  const ct = req.headers.get('content-type') ?? ''
  if (ct.includes('multipart/form-data')) {
    const fd = await req.formData()
    return Object.fromEntries(fd.entries())
  }
  // Read actual bytes to enforce limit for chunked requests (no Content-Length)
  const buf = await req.arrayBuffer()
  if (buf.byteLength > _MAX_BODY_SIZE) throw Object.assign(new Error('Request body too large'), { status: 413 })
  const text = new TextDecoder().decode(buf)
  if (ct.includes('application/json')) return JSON.parse(text)
  if (ct.includes('application/x-www-form-urlencoded')) return Object.fromEntries(new URLSearchParams(text))
  return {}
}

// Route-level aliases (shared across all handlers)
const _alias_json = (data, status = 200) => _json(data, status)
const _alias_html = (body, status = 200) => _html(body, status)
const _alias_text = (body, status = 200) => _text(body, status)
const _alias_redirect = (loc, status = 302) => _redirect(loc, status)
const _alias_parseBody = (req) => _parseBody(req)
`.trim()
  }

  _sqliteSetup() {
    return `
const { Database } = require('bun:sqlite')
const _db = new Database(process.env.DATABASE_URL ?? 'app.db', { create: true })
_db.run('PRAGMA journal_mode = WAL')
_db.run('PRAGMA synchronous = normal')
`
  }

  _pgSetup() {
    return `
const { Pool } = require('pg')
const _pool = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgres://localhost/app' })
const _db = {
  run: async (sql, params = []) => { await _pool.query(sql, params) },
  query: (sql) => ({ all: async (params = []) => (await _pool.query(sql, params)).rows,
                     get: async (params = []) => (await _pool.query(sql, params)).rows[0] ?? null,
                     run: async (params = []) => { await _pool.query(sql, params) } })
}
`
  }

  // ── Schema helpers ────────────────────────────────────────────────────────────

  emitModelHelpers(schema) {
    const name = schema.name
    if (!_SAFE_IDENT.test(name)) throw new Error(`Arc codegen: unsafe schema name: ${JSON.stringify(name)}`)

    return this.isPg
      ? this._emitModelHelpersPg(schema)
      : this._emitModelHelpersSqlite(schema)
  }

  _emitModelHelpersSqlite(schema) {
    const { lc, fields, colList, colDefs } = this._schemaVars(schema, 'sqlite')
    const placeholders = fields.map((_, i) => `?${i + 1}`).join(', ')
    const updates = fields.map((f, i) => `${f.name} = ?${i + 1}`).join(', ')

    return `
// Schema: ${schema.name}
_db.run(\`CREATE TABLE IF NOT EXISTS ${lc} (${colDefs})\`)

const _q_${lc}_findMany = _db.query('SELECT * FROM ${lc} LIMIT ?1 OFFSET ?2')
const _q_${lc}_find = _db.query('SELECT * FROM ${lc} WHERE id = ?1')
${colList ? `const _q_${lc}_create = _db.query('INSERT INTO ${lc} (${colList}) VALUES (${placeholders}) RETURNING *')` : ''}
${colList ? `const _q_${lc}_update = _db.query('UPDATE ${lc} SET ${updates} WHERE id = ?${fields.length + 1} RETURNING *')` : ''}
const _q_${lc}_delete = _db.query('DELETE FROM ${lc} WHERE id = ?1')
const _q_${lc}_count = _db.query('SELECT COUNT(*) as count FROM ${lc}')

const db = Object.assign(globalThis.db ?? {}, {
  ${lc}: {
    findMany: (opts = {}) => _q_${lc}_findMany.all(opts?.limit ?? 1000, opts?.offset ?? 0),
    find: (id) => _q_${lc}_find.get(id) ?? null,
    ${colList ? `create: (data) => _q_${lc}_create.get(${fields.map(f => `data.${f.name}`).join(', ')}),` : ''}
    ${colList ? `update: (id, data) => _q_${lc}_update.get(${fields.map(f => `data.${f.name}`).join(', ')}, id),` : ''}
    delete: (id) => (_q_${lc}_delete.run(id), true),
    count: () => _q_${lc}_count.get()?.count ?? 0,
  }
})
globalThis.db = db`.trim()
  }

  _emitModelHelpersPg(schema) {
    const { lc, fields, colList, colDefs } = this._schemaVars(schema, 'postgres')
    // PostgreSQL uses $1, $2, ... placeholders and SERIAL for autoincrement
    const placeholders = fields.map((_, i) => `$${i + 1}`).join(', ')
    const updates = fields.map((f, i) => `${f.name} = $${i + 1}`).join(', ')

    return `
// Schema: ${schema.name}
;(async () => { await _db.run(\`CREATE TABLE IF NOT EXISTS ${lc} (${colDefs})\`) })().catch(e => { console.error('[arc] schema init failed:', e.message); process.exit(1) })

const db = Object.assign(globalThis.db ?? {}, {
  ${lc}: {
    findMany: async (opts = {}) => _pool.query('SELECT * FROM ${lc} LIMIT $1 OFFSET $2', [opts?.limit ?? 1000, opts?.offset ?? 0]).then(r => r.rows),
    find: async (id) => _pool.query('SELECT * FROM ${lc} WHERE id = $1', [id]).then(r => r.rows[0] ?? null),
    ${colList ? `create: async (data) => _pool.query('INSERT INTO ${lc} (${colList}) VALUES (${placeholders}) RETURNING *', [${fields.map(f => `data.${f.name}`).join(', ')}]).then(r => r.rows[0]),` : ''}
    ${colList ? `update: async (id, data) => _pool.query('UPDATE ${lc} SET ${updates} WHERE id = $${fields.length + 1} RETURNING *', [${fields.map(f => `data.${f.name}`).join(', ')}, id]).then(r => r.rows[0]),` : ''}
    delete: async (id) => { await _pool.query('DELETE FROM ${lc} WHERE id = $1', [id]); return true },
    count: async () => _pool.query('SELECT COUNT(*) as count FROM ${lc}').then(r => +r.rows[0].count),
  }
})
globalThis.db = db`.trim()
  }

  _schemaVars(schema, dialect) {
    const lc = schema.name.toLowerCase() + 's'
    const fields = (schema.fields ?? []).filter(f => f.name && !f.decorators?.includes('@id'))
    const colList = fields.map(f => f.name).join(', ')
    const idDef = dialect === 'postgres' ? 'SERIAL PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT'
    const colDefs = [
      `id ${idDef}`,
      ...fields.map(f => `${f.name} ${this.arcTypeToSql(f.typeAnnotation?.name, dialect)}`)
    ].join(', ')
    return { lc, fields, colList, colDefs }
  }

  arcTypeToSql(arcType, dialect = 'sqlite') {
    return _arcTypeToSql(arcType, dialect)
  }

  // ── Job handlers ──────────────────────────────────────────────────────────────

  emitJobHandler(job) {
    if (!_SAFE_IDENT.test(job.name)) throw new Error(`Arc codegen: unsafe job name: ${JSON.stringify(job.name)}`)
    const params = (job.params ?? []).map(p => p.name).join(', ')
    const body = job.body?.type === 'BlockStatement'
      ? this._emitRouteBody(job.body.body)
      : ''
    return `
// Job: ${job.name}
async function _job_${job.name}(${params}) {
  ${body}
}`.trim()
  }

  // ── Route-aware body emitter ──────────────────────────────────────────────────
  // In route/job bodies: response calls (json/redirect/html/text) need `return`,
  // async helpers (parseBody, auth.*, oauth.*, jwt.*) need `await`.

  // Calls that always return a Response and should be prefixed with `return`
  static _RETURN_FUNS = new Set(['json', 'redirect', 'html', 'text', 'auth.clear'])
  // Calls that return a Response and are async — prefix with `return await`
  static _RETURN_AWAIT_FUNS = new Set(['auth.set'])
  // Async call RHS in VarDecl — prefix with `await`
  static _AWAIT_FUNS = new Set([
    'parseBody',
    'auth.session', 'auth.require',
    'oauth.github.callback', 'oauth.google.callback',
    'jwt.sign', 'jwt.verify',
    'email.send',
  ])

  _calleePath(callee) {
    if (!callee) return ''
    if (callee.type === 'Identifier') return callee.name
    if (callee.type === 'MemberExpr') {
      const obj = this._calleePath(callee.object)
      const prop = callee.property?.name ?? callee.property?.value ?? ''
      return obj ? `${obj}.${prop}` : prop
    }
    return ''
  }

  _emitRouteBody(stmts) {
    if (!stmts) return ''
    if (!Array.isArray(stmts)) stmts = [stmts]
    return stmts.map(s => this._emitRouteStmt(s)).filter(Boolean).join('\n')
  }

  _emitRouteStmt(stmt) {
    if (!stmt) return ''

    if (stmt.type === 'ExprStatement') {
      const expr = stmt.expr ?? stmt.expression
      if (expr?.type === 'CallExpr') {
        const name = this._calleePath(expr.callee)
        if (BunServerEmitter._RETURN_FUNS.has(name))
          return `return ${this.jsEmitter.emitExpr(expr)};`
        if (BunServerEmitter._RETURN_AWAIT_FUNS.has(name))
          return `return await ${this.jsEmitter.emitExpr(expr)};`
        if (BunServerEmitter._AWAIT_FUNS.has(name))
          return `await ${this.jsEmitter.emitExpr(expr)};`
      }
      return `${this.jsEmitter.emitExpr(expr ?? stmt)};`
    }

    if (stmt.type === 'VarDecl') {
      const kind = stmt.kind === 'let' ? 'let' : 'const'
      if (stmt.init?.type === 'CallExpr') {
        const name = this._calleePath(stmt.init.callee)
        if (BunServerEmitter._AWAIT_FUNS.has(name))
          return `${kind} ${stmt.name} = await ${this.jsEmitter.emitExpr(stmt.init)};`
      }
      return `${kind} ${stmt.name} = ${this.jsEmitter.emitExpr(stmt.init)};`
    }

    if (stmt.type === 'MatchStatement') {
      return this._emitRouteMatch(stmt)
    }

    if (stmt.type === 'BlockStatement') {
      return `{${this._emitRouteBody(stmt.body)}}`
    }

    // ReturnStatement, IfStatement, ForStatement, etc. fall through to general emitter
    return this.jsEmitter.emitStmt(stmt)
  }

  _emitRouteArmBody(body) {
    if (!body) return ''
    if (body.type === 'BlockStatement') return this._emitRouteBody(body.body)
    if (Array.isArray(body)) return this._emitRouteBody(body)
    // Single expression arm: treat as a statement
    if (body.type === 'CallExpr') {
      const name = this._calleePath(body.callee)
      if (BunServerEmitter._RETURN_FUNS.has(name))
        return `return ${this.jsEmitter.emitExpr(body)};`
      if (BunServerEmitter._RETURN_AWAIT_FUNS.has(name))
        return `return await ${this.jsEmitter.emitExpr(body)};`
    }
    return `${this.jsEmitter.emitExpr(body)};`
  }

  _emitRouteMatch(stmt) {
    const id = (this.jsEmitter._matchCounter = (this.jsEmitter._matchCounter ?? 0) + 1)
    const subj = `_ms${id}`
    const cond = this.jsEmitter.emitExpr(stmt.subject)

    const arms = (stmt.arms ?? []).map((arm, i) => {
      const body = this._emitRouteArmBody(arm.body)
      const pfx = i === 0 ? 'if' : 'else if'

      if (!arm.pattern || arm.pattern.type === 'Wildcard') {
        return i === 0 ? `{ ${body} }` : `else { ${body} }`
      }
      if (arm.pattern.type === 'Identifier') {
        const bind = arm.pattern.name
        return i === 0 ? `{ const ${bind} = ${subj}; ${body} }` : `else { const ${bind} = ${subj}; ${body} }`
      }
      if (arm.pattern.type === 'VariantPattern') {
        const test = this.jsEmitter.emitPattern(arm.pattern, subj)
        const bind = arm.pattern.name ? `const ${arm.pattern.name} = ${subj}; ` : ''
        return `${pfx}(${test}) { ${bind}${body} }`
      }
      const test = this.jsEmitter.emitPattern(arm.pattern, subj)
      return `${pfx}(${test}) { ${body} }`
    })

    return `const ${subj} = ${cond};\n${arms.join('\n')}`
  }

  // ── Route handlers ────────────────────────────────────────────────────────────

  routeHandlerName(route) {
    const slug = route.path.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '') || 'root'
    return `_route_${route.method.toLowerCase()}_${slug}`
  }

  emitRouteHandler(route) {
    const name = this.routeHandlerName(route)
    const pathParams = (route.params ?? []).map(p => `const ${p} = params['${p}']`).join('\n  ')
    const requiresAuth = route.annotations?.includes('@auth')

    const body = route.body?.type === 'BlockStatement'
      ? this._emitRouteBody(route.body.body)
      : ''

    const authGuard = requiresAuth
      ? `const _sess = await auth.session(req); if (!_sess) return _json({ error: 'Unauthorized' }, 401);\n    const session = _sess;`
      : ''

    return `
// Route: ${route.method} ${route.path}${requiresAuth ? ' [auth]' : ''}
async function ${name}(req, params) {
  try {
    ${pathParams ? pathParams + '\n  ' : ''}${authGuard ? authGuard + '\n  ' : ''}const json = _alias_json
    const html = _alias_html
    const text = _alias_text
    const redirect = _alias_redirect
    const parseBody = _alias_parseBody
    const request = req
    ${body}
  } catch (_e) {
    if (_e?._authError) return _json({ error: 'Unauthorized' }, 401)
    if (_e?.status === 413) return _json({ error: 'Request body too large' }, 413)
    console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', traceId: req?._traceId, route: '${route.method} ${route.path}', msg: _e?.message ?? String(_e) }))
    return _json({ error: 'Internal server error' }, 500)
  }
}`.trim()
  }

  // ── Bun.serve() entry ─────────────────────────────────────────────────────────

  emitBunServe(routes, schemas) {
    const port = '+(process.env.PORT ?? 3000)'
    const hasDb = schemas && schemas.length > 0
    const _timeout2s = `new Promise((_, r) => setTimeout(() => r(new Error('timeout')), 2000))`
    const dbProbe = hasDb
      ? (this.isPg
        ? `let _dbOk=false;try{await Promise.race([_pool.query('SELECT 1'),${_timeout2s}]);_dbOk=true}catch{}`
        : `let _dbOk=false;try{await Promise.race([Promise.resolve(_db.query('SELECT 1').get()),${_timeout2s}]);_dbOk=true}catch{}`)
      : ''
    const healthBody = hasDb
      ? `${dbProbe}\n    return _json({ status: _dbOk ? 'ok' : 'degraded', db: _dbOk ? 'up' : 'down', uptime: process.uptime() }, 200, { 'Cache-Control': 'no-store, no-cache' })`
      : `return _json({ status: 'ok', uptime: process.uptime() }, 200, { 'Cache-Control': 'no-store, no-cache' })`
    return `
// Start Bun server
const _server = Bun.serve({
  port: ${port},
  async fetch(req) {
    req._traceId = req.headers.get('x-request-id') ?? crypto.randomUUID().slice(0, 8)
    const url = new URL(req.url)
    if (url.pathname === '/health') {
      try {
    ${healthBody}
      } catch (_he) { return _json({ status: 'error', msg: _he?.message }, 503, { 'Cache-Control': 'no-store, no-cache' }) }
    }
    return _dispatch(req, url)
  }
})
console.log(\`arc: server running on http://localhost:\${_server.port}\`)
`.trim()
  }
}

module.exports = { BunServerEmitter }
