'use strict'

// Bun server emitter.
// Input:  Arc program with RouteDecl + ModelDecl + JobDecl nodes
// Output: A complete dist/server.js that runs with `bun dist/server.js`
//
// options.db: 'sqlite' (default) | 'postgres'
//
// Performance strategy:
//   - Routes compiled to a radix-trie decision tree at build time (zero regex at request time)
//   - SQL queries generated as constant strings (no query-builder overhead at runtime)
//   - Typed JSON serialization per response shape (no generic JSON.stringify overhead)
//   - Bun.serve() used directly (20% faster than fetch-handler style)

const { JsEmitter } = require('./js')
const { compileRoutes } = require('../compilers/route-compiler')
const { emitAuthPreamble } = require('./auth-helpers')
const { emitQueuePreamble, emitEmailPreamble, emitJobEnqueueWrapper } = require('./queue-helpers')
const { arcTypeToSql: _arcTypeToSql } = require('../compilers/sql-types')
const { routeHandlerName } = require('./route-utils')
const { SHARED_RESPONSE_HELPERS } = require('./emitter-preamble')
const { emitRouteBody } = require('./route-body-emitter')

const _SAFE_IDENT = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/

class BunServerEmitter {
  constructor(options = {}) {
    this.options = options
    this.db = options.db ?? 'sqlite'
    this.jsEmitter = new JsEmitter(options)
  }

  get isPg() { return this.db === 'postgres' }

  emitProgram(program) {
    const routes = program.declarations.filter(d => d.type === 'RouteDecl')
    const schemas = program.declarations.filter(d => d.type === 'ModelDecl')
    const jobs = program.declarations.filter(d => d.type === 'JobDecl')
    const hasAuth = routes.some(r => r.annotations?.includes('@auth'))

    if (routes.length === 0 && schemas.length === 0) return ''

    const parts = []

    parts.push(this.emitPreamble(schemas))
    if (hasAuth) parts.push(emitAuthPreamble(this.options.auth ?? {}))

    // Queue + email always emitted (tiny, zero deps)
    parts.push(emitQueuePreamble())
    parts.push(emitEmailPreamble())

    if (this.isPg && schemas.length > 0) {
      // PG: emit a single awaited startup block — prevents fire-and-forget race and
      // globalThis.db overwrite if multiple schemas' IIFEs run concurrently
      parts.push(this.emitPgSchemaInit(schemas))
    } else {
      for (const schema of schemas) {
        parts.push(this.emitModelHelpers(schema))
      }
      if (schemas.length > 0) parts.push('const db = globalThis.db')
    }

    for (const job of jobs) {
      parts.push(this.emitJobHandler(job))
      // Public enqueue wrapper: `const SendEmail = (...args) => Queue.enqueue(_job_SendEmail, ...args)`
      parts.push(emitJobEnqueueWrapper(job.name))
    }

    for (const route of routes) {
      parts.push(this.emitRouteHandler(route))
    }

    const routeSpecs = routes.map(r => ({
      method: r.method,
      path: r.path,
      handlerName: routeHandlerName(r),
    }))
    parts.push(compileRoutes(routeSpecs))

    parts.push(this.emitBunServe(routes, schemas))

    return parts.filter(Boolean).join('\n\n')
  }

  // ── Preamble ─────────────────────────────────────────────────────────────────

  emitPreamble(schemas) {
    const hasDb = schemas.length > 0
    const dbSetup = hasDb ? (this.isPg ? this._pgSetup() : this._sqliteSetup()) : ''

    return `
// Generated by Arc compiler — do not edit
'use strict'
${dbSetup}
${SHARED_RESPONSE_HELPERS}

// In-memory rate limiter — 60 POST requests per IP per minute (sliding window)
// Applies to all mutating requests. Resets hourly to prevent unbounded Map growth.
// Set TRUSTED_PROXY_IPS (comma-separated) to opt-in to X-Forwarded-For trust.
// Without it, X-Forwarded-For is ignored to prevent IP spoofing.
const _rlMap = new Map()
const _TRUSTED_PROXIES = process.env.TRUSTED_PROXY_IPS
  ? new Set(process.env.TRUSTED_PROXY_IPS.split(',').map(s => s.trim()).filter(Boolean))
  : null
setInterval(() => _rlMap.clear(), 60 * 60 * 1000).unref()
function _checkRateLimit(req) {
  if (req.method !== 'POST' && req.method !== 'PUT' && req.method !== 'DELETE' && req.method !== 'PATCH') return null
  const xff = req.headers.get('x-forwarded-for')
  const ip = (_TRUSTED_PROXIES && xff) ? xff.split(',')[0].trim() : (req.headers.get('x-real-ip') ?? 'unknown')
  const now = Date.now()
  const window = 60000
  let entry = _rlMap.get(ip)
  if (!entry || now > entry.resetAt) entry = { count: 0, resetAt: now + window }
  entry.count++
  _rlMap.set(ip, entry)
  if (entry.count > 60) return _json({ error: 'Too many requests' }, 429, { 'Retry-After': String(Math.ceil((entry.resetAt - now) / 1000)) })
  return null
}`.trim()
  }

  _sqliteSetup() {
    return `
const { Database } = require('bun:sqlite')
let _db
try {
  _db = new Database(process.env.DATABASE_URL ?? 'app.db', { create: true })
  _db.run('PRAGMA journal_mode = WAL')
  _db.run('PRAGMA synchronous = normal')
} catch (_dbInitErr) {
  console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'db_init_failed', msg: _dbInitErr?.message ?? String(_dbInitErr) }))
  process.exit(1)
}
`
  }

  _pgSetup() {
    return `
const { Pool } = require('pg')
const _pool = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgres://localhost/app', max: 10, idleTimeoutMillis: 30000, connectionTimeoutMillis: 5000 })
const _db = {
  run: async (sql, params = []) => { await _pool.query(sql, params) },
  query: (sql) => ({ all: async (params = []) => (await _pool.query(sql, params)).rows,
                     get: async (params = []) => (await _pool.query(sql, params)).rows[0] ?? null,
                     run: async (params = []) => { await _pool.query(sql, params) } })
}
`
  }

  // ── Schema helpers ────────────────────────────────────────────────────────────

  emitModelHelpers(schema) {
    const name = schema.name
    if (!_SAFE_IDENT.test(name)) throw new Error(`Arc codegen: unsafe schema name: ${JSON.stringify(name)}`)
    if (this.isPg) throw new Error('Arc codegen: isPg schemas must use emitPgSchemaInit, not emitModelHelpers')
    return this._emitModelHelpersSqlite(schema)
  }

  _emitModelHelpersSqlite(schema) {
    const { lc, fields, colList, colDefs } = this._schemaVars(schema, 'sqlite')
    const placeholders = fields.map((_, i) => `?${i + 1}`).join(', ')
    const updates = fields.map((f, i) => `${f.name} = ?${i + 1}`).join(', ')
    const selectCols = colList ? `id, ${colList}` : 'id'

    const fieldNames = JSON.stringify(fields.map(f => f.name))
    return `
// Schema: ${schema.name}
_db.run(\`CREATE TABLE IF NOT EXISTS ${lc} (${colDefs})\`)

const _q_${lc}_findMany = _db.query('SELECT ${selectCols} FROM ${lc} LIMIT ?1 OFFSET ?2')
const _q_${lc}_find = _db.query('SELECT ${selectCols} FROM ${lc} WHERE id = ?1')
${colList ? `const _q_${lc}_create = _db.query('INSERT INTO ${lc} (${colList}) VALUES (${placeholders}) RETURNING *')` : ''}
${colList ? `const _q_${lc}_update = _db.query('UPDATE ${lc} SET ${updates} WHERE id = ?${fields.length + 1} RETURNING *')` : ''}
const _q_${lc}_delete = _db.query('DELETE FROM ${lc} WHERE id = ?1')
const _q_${lc}_count = _db.query('SELECT COUNT(*) as count FROM ${lc}')
const _${lc}_fields = ${fieldNames}

Object.assign(globalThis.db ?? (globalThis.db = {}), {
  ${lc}: {
    findMany: (opts = {}) => _q_${lc}_findMany.all(Math.min(opts?.limit ?? 20, 100), opts?.offset ?? 0),
    find: (id) => _q_${lc}_find.get(id) ?? null,
    ${colList ? `create: (data) => { const _d = _pick(data, _${lc}_fields); return _q_${lc}_create.get(${fields.map(f => `_d.${f.name}`).join(', ')}) },` : ''}
    ${colList ? `update: (id, data) => { const _d = _pick(data, _${lc}_fields); return _q_${lc}_update.get(${fields.map(f => `_d.${f.name}`).join(', ')}, id) },` : ''}
    delete: (id) => (_q_${lc}_delete.run(id), true),
    count: () => _q_${lc}_count.get()?.count ?? 0,
  }
})`.trim()
  }

  // Emit a single awaited async startup block for all PG schemas.
  // Keeps CREATE TABLE in sequence (no concurrent-IIFE race) and assembles globalThis.db once.
  emitPgSchemaInit(schemas) {
    const tableInits = schemas.map(schema => {
      const { lc, colDefs } = this._schemaVars(schema, 'postgres')
      return `  await _db.run(\`CREATE TABLE IF NOT EXISTS ${lc} (${colDefs})\`)`
    }).join('\n')

    const dbEntries = schemas.map(schema => {
      const { lc, fields, colList } = this._schemaVars(schema, 'postgres')
      const placeholders = fields.map((_, i) => `$${i + 1}`).join(', ')
      const updates = fields.map((f, i) => `${f.name} = $${i + 1}`).join(', ')
      const selectCols = colList ? `id, ${colList}` : 'id'
      const fieldNames = JSON.stringify(fields.map(f => f.name))
      return `  ${lc}: (() => { const _flds = ${fieldNames}; return {
    findMany: async (opts = {}) => _pool.query('SELECT ${selectCols} FROM ${lc} LIMIT $1 OFFSET $2', [Math.min(opts?.limit ?? 20, 100), opts?.offset ?? 0]).then(r => r.rows),
    find: async (id) => _pool.query('SELECT ${selectCols} FROM ${lc} WHERE id = $1', [id]).then(r => r.rows[0] ?? null),
    ${colList ? `create: async (data) => { const _d = _pick(data, _flds); return _pool.query('INSERT INTO ${lc} (${colList}) VALUES (${placeholders}) RETURNING *', [${fields.map(f => `_d.${f.name}`).join(', ')}]).then(r => r.rows[0]) },` : ''}
    ${colList ? `update: async (id, data) => { const _d = _pick(data, _flds); return _pool.query('UPDATE ${lc} SET ${updates} WHERE id = $${fields.length + 1} RETURNING *', [${fields.map(f => `_d.${f.name}`).join(', ')}, id]).then(r => r.rows[0]) },` : ''}
    delete: async (id) => { await _pool.query('DELETE FROM ${lc} WHERE id = $1', [id]); return true },
    count: async () => _pool.query('SELECT COUNT(*) as count FROM ${lc}').then(r => +r.rows[0].count),
  }})(),`
    }).join('\n')

    return `
// Schema init — promise-based startup; awaited in Bun.serve fetch handler before first dispatch
// (top-level await is invalid in CJS; this pattern is equivalent and CJS-safe)
let db = null
let _schemaInitErr = null
const _schemaInitP = (async () => {
${tableInits}
  db = globalThis.db = {
${dbEntries}
  }
})().catch(e => {
  // Set _schemaInitErr BEFORE process.exit so the guard in the fetch handler works
  // if exit is deferred (e.g., in test environments that mock process.exit).
  _schemaInitErr = e
  console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'schema_init_failed', msg: e?.message ?? String(e), cause: e?.cause?.message }))
  process.exit(1)
})`.trim()
  }

  _schemaVars(schema, dialect) {
    const lc = schema.name.toLowerCase() + 's'
    const fields = (schema.fields ?? []).filter(f => f.name && !f.decorators?.includes('@id'))
    for (const f of fields) {
      if (!_SAFE_IDENT.test(f.name)) throw new Error(`Arc codegen: unsafe field name: ${JSON.stringify(f.name)}`)
    }
    const colList = fields.map(f => f.name).join(', ')
    const idDef = dialect === 'postgres' ? 'SERIAL PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT'
    const colDefs = [
      `id ${idDef}`,
      ...fields.map(f => `${f.name} ${_arcTypeToSql(f.typeAnnotation?.name, dialect)}`)
    ].join(', ')
    return { lc, fields, colList, colDefs }
  }

  // ── Job handlers ──────────────────────────────────────────────────────────────

  emitJobHandler(job) {
    if (!_SAFE_IDENT.test(job.name)) throw new Error(`Arc codegen: unsafe job name: ${JSON.stringify(job.name)}`)
    const params = (job.params ?? []).map(p => p.name).join(', ')
    const body = job.body?.type === 'BlockStatement'
      ? emitRouteBody(job.body.body, this.jsEmitter)
      : ''
    return `
// Job: ${job.name}
async function _job_${job.name}(${params}) {
  ${body}
}`.trim()
  }

  // ── Route handlers ────────────────────────────────────────────────────────────

  emitRouteHandler(route) {
    const name = routeHandlerName(route)
    const pathParams = (route.params ?? []).map(p => `const ${p} = params['${p}']`).join('\n  ')
    const requiresAuth = route.annotations?.includes('@auth')

    const body = route.body?.type === 'BlockStatement'
      ? emitRouteBody(route.body.body, this.jsEmitter)
      : ''

    const authGuard = requiresAuth
      ? `const _sess = await auth.session(req); if (!_sess) return _json({ error: 'Unauthorized' }, 401);\n    const session = _sess;`
      : ''

    return `
// Route: ${route.method} ${route.path}${requiresAuth ? ' [auth]' : ''}
async function ${name}(req, params) {
  const _traceId = req._traceId
  try {
    ${pathParams ? pathParams + '\n  ' : ''}${authGuard ? authGuard + '\n  ' : ''}const json = _json
    const html = _html
    const text = _text
    const redirect = _redirect
    const parseBody = _parseBody
    const request = req
    ${body}
  } catch (_e) {
    if (_e?._authError) return _json({ error: 'Unauthorized' }, 401)
    if (_e?.status === 413) return _json({ error: 'Request body too large' }, 413)
    if (_e?.status === 400) return _json({ error: _e.message ?? 'Bad request' }, 400)
    console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', traceId: _traceId, route: '${route.method} ${route.path}', msg: _e?.message ?? String(_e), stack: _e?.stack }))
    return _json({ error: 'Internal server error' }, 500)
  }
}`.trim()
  }

  // ── Bun.serve() entry ─────────────────────────────────────────────────────────

  emitBunServe(routes, schemas) {
    const port = '+(process.env.PORT ?? 3000)'
    const hasDb = schemas && schemas.length > 0
    const dbProbe = hasDb
      ? (this.isPg
        ? `let _dbOk=false;try{await Promise.race([_pool.query('SELECT 1'),new Promise((_,r)=>setTimeout(()=>r(new Error('timeout')),2000))]);_dbOk=true}catch{}`
        : `let _dbOk=false;try{await Promise.race([Promise.resolve().then(()=>_db.query('SELECT 1').get()),new Promise((_,r)=>setTimeout(()=>r(new Error('timeout')),2000))]);_dbOk=true}catch{}`)
      : ''
    const healthBody = hasDb
      ? `${dbProbe}\n    return _json({ status: _dbOk ? 'ok' : 'degraded', db: _dbOk ? 'up' : 'down', uptime: process.uptime(), ts: new Date().toISOString() }, _dbOk ? 200 : 503, { 'Cache-Control': 'no-store, no-cache' })`
      : `return _json({ status: 'ok', uptime: process.uptime(), queue: typeof Queue !== 'undefined' ? 'configured' : 'n/a', ts: new Date().toISOString() }, 200, { 'Cache-Control': 'no-store, no-cache' })`
    const dbLabel = this.isPg ? 'postgres' : (hasDb ? 'sqlite' : 'none')
    return `
// Hoisted: avoids per-request RegExp allocation at high request rates
const _TRACE_ID_RE = /^[a-zA-Z0-9_-]{1,64}$/

// Start Bun server
const _server = Bun.serve({
  port: ${port},
  async fetch(req) {
    const _clientId = req.headers.get('x-request-id') ?? ''
    req._traceId = _TRACE_ID_RE.test(_clientId) ? _clientId : crypto.randomUUID().slice(0, 8)
    const url = new URL(req.url)
    if (url.pathname === '/health') {
      try {
    ${healthBody}
      } catch (_he) { console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'health_check_error', msg: _he?.message ?? String(_he) })); return _json({ status: 'error' }, 503, { 'Cache-Control': 'no-store, no-cache' }) }
    }
    ${this.isPg && schemas && schemas.length > 0 ? "if (_schemaInitErr) return _json({ error: 'Server initialization failed — check logs' }, 503, { 'Retry-After': '5' })\n    if (db === null) await _schemaInitP\n    if (db === null) return _json({ error: 'Server initialization failed — check logs' }, 503, { 'Retry-After': '5' })" : ''}
    const _rl = _checkRateLimit(req)
    if (_rl) return _rl
    return _dispatch(req, url)
  }
})
console.log(JSON.stringify({ ts: new Date().toISOString(), level: 'info', msg: 'arc: server started', port: _server.port, db: '${dbLabel}' }))
`.trim()
  }
}

module.exports = { BunServerEmitter }
