'use strict'

// Bun server emitter.
// Input:  Arc program with RouteDecl + ModelDecl + JobDecl nodes
// Output: A complete dist/server.js that runs with `bun dist/server.js`
//
// options.db: 'sqlite' (default) | 'postgres'
//
// Performance strategy:
//   - Routes compiled to a radix-trie decision tree at build time (zero regex at request time)
//   - SQL queries generated as constant strings (no query-builder overhead at runtime)
//   - Typed JSON serialization per response shape (no generic JSON.stringify overhead)
//   - Bun.serve() used directly (20% faster than fetch-handler style)

const { JsEmitter } = require('./js')
const { compileRoutes } = require('../compilers/route-compiler')
const { emitAuthPreamble } = require('./auth-helpers')
const { emitQueuePreamble, emitEmailPreamble, emitJobEnqueueWrapper } = require('./queue-helpers')
const { arcTypeToSql: _arcTypeToSql } = require('../compilers/sql-types')
const { routeHandlerName } = require('./route-utils')
const { SHARED_RESPONSE_HELPERS } = require('./emitter-preamble')
const { emitRouteBody } = require('./route-body-emitter')

const _SAFE_IDENT = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/

class BunServerEmitter {
  constructor(options = {}) {
    this.options = options
    this.db = options.db ?? 'sqlite'
    this.jsEmitter = new JsEmitter(options)
  }

  get isPg() { return this.db === 'postgres' }

  emitProgram(program) {
    const routes = program.declarations.filter(d => d.type === 'RouteDecl')
    const schemas = program.declarations.filter(d => d.type === 'ModelDecl')
    const jobs = program.declarations.filter(d => d.type === 'JobDecl')
    const hasAuth = routes.some(r => r.annotations?.includes('@auth'))

    if (routes.length === 0 && schemas.length === 0) return ''

    const parts = []

    parts.push(this.emitPreamble(schemas))
    if (hasAuth) parts.push(emitAuthPreamble(this.options.auth ?? {}))

    // Queue + email always emitted (tiny, zero deps)
    parts.push(emitQueuePreamble())
    parts.push(emitEmailPreamble())

    for (const schema of schemas) {
      parts.push(this.emitModelHelpers(schema))
    }

    for (const job of jobs) {
      parts.push(this.emitJobHandler(job))
      // Public enqueue wrapper: `const SendEmail = (...args) => Queue.enqueue(_job_SendEmail, ...args)`
      parts.push(emitJobEnqueueWrapper(job.name))
    }

    for (const route of routes) {
      parts.push(this.emitRouteHandler(route))
    }

    const routeSpecs = routes.map(r => ({
      method: r.method,
      path: r.path,
      handlerName: routeHandlerName(r),
    }))
    parts.push(compileRoutes(routeSpecs))

    parts.push(this.emitBunServe(routes, schemas))

    return parts.filter(Boolean).join('\n\n')
  }

  // ── Preamble ─────────────────────────────────────────────────────────────────

  emitPreamble(schemas) {
    const hasDb = schemas.length > 0
    const dbSetup = hasDb ? (this.isPg ? this._pgSetup() : this._sqliteSetup()) : ''

    return `
// Generated by Arc compiler — do not edit
'use strict'
${dbSetup}
${SHARED_RESPONSE_HELPERS}`.trim()
  }

  _sqliteSetup() {
    return `
const { Database } = require('bun:sqlite')
const _db = new Database(process.env.DATABASE_URL ?? 'app.db', { create: true })
_db.run('PRAGMA journal_mode = WAL')
_db.run('PRAGMA synchronous = normal')
`
  }

  _pgSetup() {
    return `
const { Pool } = require('pg')
const _pool = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgres://localhost/app' })
const _db = {
  run: async (sql, params = []) => { await _pool.query(sql, params) },
  query: (sql) => ({ all: async (params = []) => (await _pool.query(sql, params)).rows,
                     get: async (params = []) => (await _pool.query(sql, params)).rows[0] ?? null,
                     run: async (params = []) => { await _pool.query(sql, params) } })
}
`
  }

  // ── Schema helpers ────────────────────────────────────────────────────────────

  emitModelHelpers(schema) {
    const name = schema.name
    if (!_SAFE_IDENT.test(name)) throw new Error(`Arc codegen: unsafe schema name: ${JSON.stringify(name)}`)

    return this.isPg
      ? this._emitModelHelpersPg(schema)
      : this._emitModelHelpersSqlite(schema)
  }

  _emitModelHelpersSqlite(schema) {
    const { lc, fields, colList, colDefs } = this._schemaVars(schema, 'sqlite')
    const placeholders = fields.map((_, i) => `?${i + 1}`).join(', ')
    const updates = fields.map((f, i) => `${f.name} = ?${i + 1}`).join(', ')

    return `
// Schema: ${schema.name}
_db.run(\`CREATE TABLE IF NOT EXISTS ${lc} (${colDefs})\`)

const _q_${lc}_findMany = _db.query('SELECT * FROM ${lc} LIMIT ?1 OFFSET ?2')
const _q_${lc}_find = _db.query('SELECT * FROM ${lc} WHERE id = ?1')
${colList ? `const _q_${lc}_create = _db.query('INSERT INTO ${lc} (${colList}) VALUES (${placeholders}) RETURNING *')` : ''}
${colList ? `const _q_${lc}_update = _db.query('UPDATE ${lc} SET ${updates} WHERE id = ?${fields.length + 1} RETURNING *')` : ''}
const _q_${lc}_delete = _db.query('DELETE FROM ${lc} WHERE id = ?1')
const _q_${lc}_count = _db.query('SELECT COUNT(*) as count FROM ${lc}')

const db = Object.assign(globalThis.db ?? {}, {
  ${lc}: {
    findMany: (opts = {}) => _q_${lc}_findMany.all(opts?.limit ?? 1000, opts?.offset ?? 0),
    find: (id) => _q_${lc}_find.get(id) ?? null,
    ${colList ? `create: (data) => _q_${lc}_create.get(${fields.map(f => `data.${f.name}`).join(', ')}),` : ''}
    ${colList ? `update: (id, data) => _q_${lc}_update.get(${fields.map(f => `data.${f.name}`).join(', ')}, id),` : ''}
    delete: (id) => (_q_${lc}_delete.run(id), true),
    count: () => _q_${lc}_count.get()?.count ?? 0,
  }
})
globalThis.db = db`.trim()
  }

  _emitModelHelpersPg(schema) {
    const { lc, fields, colList, colDefs } = this._schemaVars(schema, 'postgres')
    // PostgreSQL uses $1, $2, ... placeholders and SERIAL for autoincrement
    const placeholders = fields.map((_, i) => `$${i + 1}`).join(', ')
    const updates = fields.map((f, i) => `${f.name} = $${i + 1}`).join(', ')

    return `
// Schema: ${schema.name}
;(async () => { await _db.run(\`CREATE TABLE IF NOT EXISTS ${lc} (${colDefs})\`) })().catch(e => { console.error('[arc] schema init failed:', e.message); process.exit(1) })

const db = Object.assign(globalThis.db ?? {}, {
  ${lc}: {
    findMany: async (opts = {}) => _pool.query('SELECT * FROM ${lc} LIMIT $1 OFFSET $2', [opts?.limit ?? 1000, opts?.offset ?? 0]).then(r => r.rows),
    find: async (id) => _pool.query('SELECT * FROM ${lc} WHERE id = $1', [id]).then(r => r.rows[0] ?? null),
    ${colList ? `create: async (data) => _pool.query('INSERT INTO ${lc} (${colList}) VALUES (${placeholders}) RETURNING *', [${fields.map(f => `data.${f.name}`).join(', ')}]).then(r => r.rows[0]),` : ''}
    ${colList ? `update: async (id, data) => _pool.query('UPDATE ${lc} SET ${updates} WHERE id = $${fields.length + 1} RETURNING *', [${fields.map(f => `data.${f.name}`).join(', ')}, id]).then(r => r.rows[0]),` : ''}
    delete: async (id) => { await _pool.query('DELETE FROM ${lc} WHERE id = $1', [id]); return true },
    count: async () => _pool.query('SELECT COUNT(*) as count FROM ${lc}').then(r => +r.rows[0].count),
  }
})
globalThis.db = db`.trim()
  }

  _schemaVars(schema, dialect) {
    const lc = schema.name.toLowerCase() + 's'
    const fields = (schema.fields ?? []).filter(f => f.name && !f.decorators?.includes('@id'))
    for (const f of fields) {
      if (!_SAFE_IDENT.test(f.name)) throw new Error(`Arc codegen: unsafe field name: ${JSON.stringify(f.name)}`)
    }
    const colList = fields.map(f => f.name).join(', ')
    const idDef = dialect === 'postgres' ? 'SERIAL PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT'
    const colDefs = [
      `id ${idDef}`,
      ...fields.map(f => `${f.name} ${_arcTypeToSql(f.typeAnnotation?.name, dialect)}`)
    ].join(', ')
    return { lc, fields, colList, colDefs }
  }

  // ── Job handlers ──────────────────────────────────────────────────────────────

  emitJobHandler(job) {
    if (!_SAFE_IDENT.test(job.name)) throw new Error(`Arc codegen: unsafe job name: ${JSON.stringify(job.name)}`)
    const params = (job.params ?? []).map(p => p.name).join(', ')
    const body = job.body?.type === 'BlockStatement'
      ? emitRouteBody(job.body.body, this.jsEmitter)
      : ''
    return `
// Job: ${job.name}
async function _job_${job.name}(${params}) {
  ${body}
}`.trim()
  }

  // ── Route handlers ────────────────────────────────────────────────────────────

  emitRouteHandler(route) {
    const name = routeHandlerName(route)
    const pathParams = (route.params ?? []).map(p => `const ${p} = params['${p}']`).join('\n  ')
    const requiresAuth = route.annotations?.includes('@auth')

    const body = route.body?.type === 'BlockStatement'
      ? emitRouteBody(route.body.body, this.jsEmitter)
      : ''

    const authGuard = requiresAuth
      ? `const _sess = await auth.session(req); if (!_sess) return _json({ error: 'Unauthorized' }, 401);\n    const session = _sess;`
      : ''

    return `
// Route: ${route.method} ${route.path}${requiresAuth ? ' [auth]' : ''}
async function ${name}(req, params) {
  const _traceId = req._traceId
  try {
    ${pathParams ? pathParams + '\n  ' : ''}${authGuard ? authGuard + '\n  ' : ''}const json = _json
    const html = _html
    const text = _text
    const redirect = _redirect
    const parseBody = _parseBody
    const request = req
    ${body}
  } catch (_e) {
    if (_e?._authError) return _json({ error: 'Unauthorized' }, 401)
    if (_e?.status === 413) return _json({ error: 'Request body too large' }, 413)
    console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', traceId: _traceId, route: '${route.method} ${route.path}', msg: _e?.message ?? String(_e) }))
    return _json({ error: 'Internal server error' }, 500)
  }
}`.trim()
  }

  // ── Bun.serve() entry ─────────────────────────────────────────────────────────

  emitBunServe(routes, schemas) {
    const port = '+(process.env.PORT ?? 3000)'
    const hasDb = schemas && schemas.length > 0
    const _timeout2s = `new Promise((_, r) => setTimeout(() => r(new Error('timeout')), 2000))`
    const dbProbe = hasDb
      ? (this.isPg
        ? `let _dbOk=false;try{await Promise.race([_pool.query('SELECT 1'),${_timeout2s}]);_dbOk=true}catch{}`
        : `let _dbOk=false;try{await Promise.race([new Promise((res,rej)=>{try{_db.query('SELECT 1').get();res()}catch(e){rej(e)}}),${_timeout2s}]);_dbOk=true}catch{}`)
      : ''
    const healthBody = hasDb
      ? `${dbProbe}\n    return _json({ status: _dbOk ? 'ok' : 'degraded', db: _dbOk ? 'up' : 'down', uptime: process.uptime() }, 200, { 'Cache-Control': 'no-store, no-cache' })`
      : `return _json({ status: 'ok', uptime: process.uptime() }, 200, { 'Cache-Control': 'no-store, no-cache' })`
    return `
// Start Bun server
const _server = Bun.serve({
  port: ${port},
  async fetch(req) {
    const _clientId = req.headers.get('x-request-id') ?? ''
    req._traceId = /^[a-zA-Z0-9_-]{1,64}$/.test(_clientId) ? _clientId : crypto.randomUUID().slice(0, 8)
    const url = new URL(req.url)
    if (url.pathname === '/health') {
      try {
    ${healthBody}
      } catch (_he) { return _json({ status: 'error', msg: _he?.message }, 503, { 'Cache-Control': 'no-store, no-cache' }) }
    }
    return _dispatch(req, url)
  }
})
console.log(\`arc: server running on http://localhost:\${_server.port}\`)
`.trim()
  }
}

module.exports = { BunServerEmitter }
