'use strict'

const fs = require('fs')
const path = require('path')

const _C = process.stdout.isTTY && !process.env.NO_COLOR
const _CYAN  = _C ? '\x1b[36m' : ''
const _GREEN = _C ? '\x1b[32m' : ''
const _DIM   = _C ? '\x1b[2m'  : ''
const _RED   = _C ? '\x1b[31m' : ''
const _RST   = _C ? '\x1b[0m'  : ''

const _PKG_ROOT = path.join(__dirname, '..', '..', 'packages', 'arc-cms')
const _SRC_WIDGETS = path.join(_PKG_ROOT, 'src', 'widgets')
const _SRC_PAGES   = path.join(_PKG_ROOT, 'src', 'pages')
const _SRC_SCHEMA  = path.join(_PKG_ROOT, 'src', 'schema')
const _SRC_SERVER  = path.join(_PKG_ROOT, 'src', 'server')

// ── Per-type block editor codegen ────────────────────────────────────────────
// Reads block-types.json and emits one admin/blocks/{type}.arc per type, each
// with explicit @state vars for every field in the schema. Arrays and selects
// are flattened to textarea fallback for v1 to keep generated code simple.
function _esc(s) { return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') }

function generateTypeEditor(typeKey, schema) {
  const label = schema.label ?? typeKey
  const fields = (schema.fields ?? []).filter(f => f.type !== 'array')
  const arrayFields = (schema.fields ?? []).filter(f => f.type === 'array')

  const stateLines = fields.map(f => {
    const defaultVal = f.type === 'select' ? `"${_esc((f.options ?? [''])[0])}"` : '""'
    return `  @state let f_${f.name} = (meta.data.${f.name} ?? ${defaultVal})`
  }).join('\n')

  const arrayState = arrayFields.length
    ? arrayFields.map(f => `  @state let f_${f.name} = JSON.stringify(meta.data.${f.name} ?? [])`).join('\n')
    : ''

  const fieldFnArgs = fields.map(f => `${f.name}: String`).concat(arrayFields.map(f => `${f.name}: String`)).join(', ')
  const dataObj = [
    ...fields.map(f => `${f.name}: ${f.name}`),
    ...arrayFields.map(f => `${f.name}: JSON.parse(${f.name})`)
  ].join(', ')

  // Children of `col class="!card" ... ` (indent 8) should sit at indent 10.
  const formRows = fields.map(f => {
    const lbl = _esc(f.label ?? f.name)
    const req = f.required ? 'true' : 'false'
    if (f.type === 'textarea') {
      return `          col gap="6px"
            text class="!input-label ${f.required ? '!input-label--required' : ''}" "${lbl}"
            textarea class="!input ${f.mono ? 'cms-mono' : ''}" bind:value="f_${f.name}" rows="${f.mono ? '10' : '5'}"`
    }
    if (f.type === 'select') {
      const opts = (f.options ?? []).map(o => `              option value="${_esc(o)}" "${_esc(o)}"`).join('\n')
      return `          col gap="6px"
            text class="!input-label ${f.required ? '!input-label--required' : ''}" "${lbl}"
            select class="!input" bind:value="f_${f.name}"
${opts}`
    }
    const inputType = f.type === 'url' ? 'url' : (f.type === 'number' ? 'number' : (f.type === 'email' ? 'email' : 'text'))
    return `          CmsField label="${lbl}" name="f_${f.name}" type="${inputType}" required="${req}"`
  }).join('\n')

  const arrayRows = arrayFields.map(f => {
    const lbl = _esc(f.label ?? f.name)
    const hint = f.of ? `Array of objects: ${Object.keys(f.of).join(', ')}` : 'Array of items'
    return `          col gap="6px"
            text class="!input-label" "${lbl}"
            text class="cms-hint" "${hint} (one JSON object per line, or a JSON array)"
            textarea class="!input cms-mono" bind:value="f_${f.name}" rows="8"`
  }).join('\n')

  const saveArgs = fields.map(f => `f_${f.name}`).concat(arrayFields.map(f => `f_${f.name}`)).join(', ')

  return `import CmsLayout from "site/cms/CmsLayout.arc"
import CmsPageHeader from "site/cms/CmsPageHeader.arc"
import CmsField from "site/cms/CmsField.arc"

# Auto-generated by arc cms init from server/block-types.json
# Schema-driven editor for "${typeKey}" blocks. Re-run cms init to regenerate.
page "Edit ${label} block - Admin"

  @param id

  @server fn getBlock(blockId: String) -> Any
    const blk = db.pageblocks.find(blockId)
    const parsed = JSON.parse(blk.data ?? "{}")
    return { block: blk, data: parsed }

  @live const meta = getBlock(id)

  @state let pageName = meta.block.page
  @state let visible  = meta.block.visible
  @state let deleted  = false
${stateLines}${arrayState ? '\n' + arrayState : ''}

  @server fn save(blockId: String, p: String, v: Bool, ${fieldFnArgs}) -> Any
    if !session || (session.role != "admin" && session.role != "editor")
      return { error: "forbidden" }
    const data = JSON.stringify({ ${dataObj} })
    db.pageblocks.update(blockId, { page: p, visible: v, data: data })
    db.auditlogs.create({ actorId: session.userId, action: "update", entityType: "PageBlock", entityId: blockId, after: data })
    return { ok: true }

  @server fn deleteBlock(blockId: String) -> Any
    if !session || (session.role != "admin" && session.role != "editor")
      return { error: "forbidden" }
    db.pageblocks.delete(blockId)
    db.auditlogs.create({ actorId: session.userId, action: "delete", entityType: "PageBlock", entityId: blockId })
    return { ok: true }

  CmsLayout title="Edit ${label} block" active="blocks"
    if deleted
      col class="!card" p="24px"
        text "Block deleted."
        link href="/admin/blocks"
          button class="!btn !btn--ghost" "Back to blocks"

    if !deleted
      CmsPageHeader title="${label} block" subtitle="on page: {pageName}"
        link href="/admin/blocks/{id}"
          button class="!btn !btn--ghost" "Raw JSON editor"
        link href="/admin/blocks"
          button class="!btn !btn--ghost" "Back"

      row class="cms-editor" gap="24px"
        col class="!card" p="24px" gap="14px" style="flex:1; min-width:0"
          CmsField label="Page slug" name="pageName" required="true"
          row gap="10px" align="center"
            input type="checkbox" bind:checked="visible"
            text class="!input-label" "Visible"

          text class="cms-section" "${label} fields"
${formRows || '          text class="cms-hint" "No simple fields defined."'}${arrayRows ? '\n\n          text class="cms-section" "Lists"\n' + arrayRows : ''}

          row gap="10px"
            button class="!btn !btn--primary" on:click={ save(id, pageName, visible, ${saveArgs}) } "Save"
            button class="!btn !btn--danger" on:click={ @deleted = (confirm("Delete block?") && deleteBlock(id).ok == true) } "Delete"

        col class="cms-preview" style="flex:1; min-width:0"
          text class="cms-section" "Live preview"
          iframe src="/{pageName}?preview=1" class="cms-preview-frame"

  design
    .cms-editor
      align-items: stretch
    .cms-section
      font-size: 12px
      font-weight: 700
      text-transform: uppercase
      letter-spacing: 0.07em
      color: var(--ui-fg-3, #a3a3a3)
      margin: 4px 0
    .cms-hint
      font-size: 12px
      color: var(--ui-fg-3, #a3a3a3)
      margin: 0
    .cms-mono
      font-family: ui-monospace, 'SF Mono', Consolas, monospace
      font-size: 12px
    .cms-preview
      display: flex
      flex-direction: column
      gap: 8px
    .cms-preview-frame
      width: 100%
      flex: 1
      min-height: 420px
      border: 1px solid var(--ui-border, #e5e5e5)
      border-radius: 12px
      background-color: #fff
`
}

function generateAllBlockEditors(absDir, log, force) {
  const schemaFile = path.join(absDir, 'server', 'block-types.json')
  if (!fs.existsSync(schemaFile)) return
  let schema
  try {
    schema = JSON.parse(fs.readFileSync(schemaFile, 'utf8'))
  } catch (err) {
    log.warnings = log.warnings ?? []
    log.warnings.push(`could not parse server/block-types.json: ${err.message}`)
    return
  }
  const blocksDir = path.join(absDir, 'admin', 'blocks')
  for (const [typeKey, typeSchema] of Object.entries(schema)) {
    if (!/^[a-z][a-z0-9_-]*$/.test(typeKey)) {
      log.warnings = log.warnings ?? []
      log.warnings.push(`skipping invalid block type key: "${typeKey}"`)
      continue
    }
    const typeDir = path.join(blocksDir, typeKey)
    fs.mkdirSync(typeDir, { recursive: true })
    const dest = path.join(typeDir, '[id].arc')
    if (fs.existsSync(dest) && !force) {
      log.skipped.push(dest)
      continue
    }
    fs.writeFileSync(dest, generateTypeEditor(typeKey, typeSchema))
    log.created.push(dest)
  }
}

function _copyDir(src, dest, log, force) {
  if (!fs.existsSync(src)) return
  fs.mkdirSync(dest, { recursive: true })
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name)
    const d = path.join(dest, entry.name)
    if (entry.isDirectory()) {
      _copyDir(s, d, log, force)
    } else {
      if (fs.existsSync(d) && !force) {
        log.skipped.push(d)
        continue
      }
      fs.copyFileSync(s, d)
      log.created.push(d)
    }
  }
}

async function cmsInit(projectDir, opts = {}) {
  const absDir = path.resolve(projectDir || '.')
  const _t0 = Date.now()
  const force = !!opts.force

  if (!fs.existsSync(absDir)) {
    console.error(`${_RED}arc cms init: directory not found: ${absDir}${_RST}`)
    process.exit(1)
  }

  const log = { created: [], skipped: [] }

  // 1. Copy widgets → <project>/site/cms/
  _copyDir(_SRC_WIDGETS, path.join(absDir, 'site', 'cms'), log, force)

  // 2. Copy admin pages → <project>/admin/
  _copyDir(_SRC_PAGES, path.join(absDir, 'admin'), log, force)

  // 3. Copy schema (block-types.json + cms.config.arc template)
  const schemaDest = path.join(absDir, 'server')
  fs.mkdirSync(schemaDest, { recursive: true })
  for (const file of ['block-types.json', 'admin-roles.json']) {
    const s = path.join(_SRC_SCHEMA, file)
    const d = path.join(schemaDest, file)
    if (fs.existsSync(s) && (!fs.existsSync(d) || force)) {
      fs.copyFileSync(s, d)
      log.created.push(d)
    } else if (fs.existsSync(d)) {
      log.skipped.push(d)
    }
  }
  const cfgTemplate = path.join(_SRC_SCHEMA, 'cms.config.arc.template')
  const cfgDest     = path.join(absDir, 'cms.config.arc')
  if (fs.existsSync(cfgTemplate) && (!fs.existsSync(cfgDest) || force)) {
    fs.copyFileSync(cfgTemplate, cfgDest)
    log.created.push(cfgDest)
  } else if (fs.existsSync(cfgDest)) {
    log.skipped.push(cfgDest)
  }

  // 4. Copy server helpers
  const serverDest = path.join(absDir, 'server', 'cms')
  _copyDir(_SRC_SERVER, serverDest, log, force)

  // 4b. Generate per-type block editors from block-types.json
  generateAllBlockEditors(absDir, log, force)

  // 5. Ensure arc-ui CSS is available at public/arc-ui/arc-ui.css.
  // Prefer node_modules; fall back to a sibling checkout (dev environments).
  const _arcUiCandidates = [
    path.join(absDir, 'node_modules', '@arc-lang', 'arc-ui', 'index.css'),
    path.join(absDir, '..', 'arc-ui', 'index.css'),
    path.join(__dirname, '..', '..', '..', 'arc-ui', 'index.css'),
  ]
  const _arcUiSrc = _arcUiCandidates.find(p => fs.existsSync(p))
  const _arcUiDest = path.join(absDir, 'public', 'arc-ui', 'arc-ui.css')
  if (_arcUiSrc && !fs.existsSync(_arcUiDest)) {
    fs.mkdirSync(path.dirname(_arcUiDest), { recursive: true })
    // Inline imports - arc-ui's index.css uses @import; resolve them recursively so the file is self-contained.
    // Imports are bounded within the arc-ui package directory to prevent traversal.
    const _arcUiRoot = path.dirname(path.resolve(_arcUiSrc))
    const _inlineSeen = new Set()
    const _inline = src => {
      const abs = path.resolve(src)
      if (_inlineSeen.has(abs)) return ''
      _inlineSeen.add(abs)
      let txt
      try { txt = fs.readFileSync(abs, 'utf8') } catch { return '' }
      const dir = path.dirname(abs)
      return txt.replace(/@import\s+["']([^"']+)["'];?/g, (_, rel) => {
        const sub = path.resolve(dir, rel)
        // Bound imports within the arc-ui root to prevent path traversal
        if (!sub.startsWith(_arcUiRoot + path.sep) && sub !== path.resolve(_arcUiSrc)) return ''
        return fs.existsSync(sub) ? _inline(sub) : ''
      })
    }
    fs.writeFileSync(_arcUiDest, _inline(_arcUiSrc))
    log.created.push(_arcUiDest)
    // Also copy the JS files (toast, modal, etc.)
    const _jsSrc = path.join(path.dirname(_arcUiSrc), 'js')
    const _jsDest = path.join(path.dirname(_arcUiDest), 'js')
    if (fs.existsSync(_jsSrc)) {
      _copyDir(_jsSrc, _jsDest, log, force)
    }
  } else if (fs.existsSync(_arcUiDest)) {
    log.skipped.push(_arcUiDest)
  } else {
    log.warnings = log.warnings ?? []
    log.warnings.push('arc-ui CSS not found — install @arc-lang/arc-ui or copy index.css to public/arc-ui/arc-ui.css')
  }

  // 6. Print summary
  const rel = p => path.relative(process.cwd(), p)
  const elapsed = Date.now() - _t0

  if (_C) {
    console.log(`\n  ${_CYAN}⚡ arc cms init${_RST}\n`)
    for (const f of log.created.slice(0, 30)) {
      console.log(`  ${_GREEN}+${_RST} ${rel(f)}`)
    }
    if (log.created.length > 30) {
      console.log(`  ${_DIM}… and ${log.created.length - 30} more${_RST}`)
    }
    for (const f of log.skipped.slice(0, 10)) {
      console.log(`  ${_DIM}· ${rel(f)} (already exists, skipped)${_RST}`)
    }
    if (log.skipped.length > 10) {
      console.log(`  ${_DIM}… and ${log.skipped.length - 10} more skipped${_RST}`)
    }
    for (const w of (log.warnings ?? [])) {
      console.log(`  ${_RED}!${_RST} ${w}`)
    }
    console.log(`\n  ${_GREEN}✓${_RST}  ${log.created.length} files created${log.skipped.length ? `, ${log.skipped.length} skipped` : ''} in ${_DIM}${elapsed}ms${_RST}`)
    console.log(`  ${_DIM}↳  next: arc build-site . && arc build-server .${_RST}\n`)
  } else {
    for (const f of log.created) console.log(`arc cms init: created ${rel(f)}`)
    for (const f of log.skipped) console.log(`arc cms init: skipped ${rel(f)} (exists)`)
  }
}

module.exports = { cmsInit }
