'use strict'

const fs = require('fs')
const path = require('path')
const { Lexer } = require('../lexer')
const { Parser } = require('../parser')
const { findArcFiles } = require('../utils/fs')

const _C = process.stdout.isTTY && !process.env.NO_COLOR
const _CYAN  = _C ? '\x1b[36m' : ''
const _GREEN = _C ? '\x1b[32m' : ''
const _DIM   = _C ? '\x1b[2m'  : ''
const _RST   = _C ? '\x1b[0m'  : ''

function _pluralize(name) {
  const lower = name.toLowerCase()
  if (lower.endsWith('y') && !/[aeiou]y$/.test(lower)) return lower.slice(0, -1) + 'ies'
  if (lower.endsWith('s') || lower.endsWith('x') || lower.endsWith('z') || lower.endsWith('ch') || lower.endsWith('sh')) return lower + 'es'
  return lower + 's'
}

function _fieldToInputType(field) {
  const t = (field.typeAnnotation?.name ?? '').replace(/\?$/, '')
  if (t === 'Bool') return 'checkbox'
  if (t === 'Int' || t === 'Float') return 'number'
  if (t === 'DateTime') return 'datetime-local'
  if (t === 'Email') return 'email'
  if (t === 'Text') return 'textarea'
  return 'text'
}

function _parseFieldsArg(fieldsStr) {
  if (!fieldsStr) return [{ name: 'title', type: 'String', optional: false }, { name: 'body', type: 'Text', optional: false }]
  return fieldsStr.trim().split(/\s+/).map(part => {
    const optional = part.endsWith('?')
    const clean = optional ? part.slice(0, -1) : part
    const [name, type = 'String'] = clean.split(':')
    if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
      console.error(`arc scaffold: invalid field name "${name}" — use letters, numbers, underscores`)
      process.exit(1)
    }
    return { name, type, optional }
  })
}

function _editableFields(model) {
  return (model.fields ?? []).filter(f =>
    f.name && !f.decorators?.includes('@id')
  )
}

function _primaryField(model) {
  const fields = _editableFields(model)
  const strField = fields.find(f => {
    const t = (f.typeAnnotation?.name ?? '').replace(/\?$/, '')
    return t === 'String' || t === 'Email'
  })
  return (strField ?? fields[0])?.name ?? 'id'
}

function _findModel(modelName, absDir) {
  const serverDir = fs.existsSync(path.join(absDir, 'server'))
    ? path.join(absDir, 'server')
    : absDir
  for (const file of findArcFiles(serverDir)) {
    let src
    try { src = fs.readFileSync(file, 'utf8') }
    catch { continue }
    try {
      const tokens = new Lexer(src, file).tokenize()
      const program = new Parser(tokens, file).parse()
      const model = program.declarations.find(
        d => d.type === 'ModelDecl' && d.name.toLowerCase() === modelName.toLowerCase()
      )
      if (model) return model
    } catch { continue }
  }
  return null
}

function _findAllModels(absDir) {
  const serverDir = fs.existsSync(path.join(absDir, 'server'))
    ? path.join(absDir, 'server')
    : absDir
  const models = []
  for (const file of findArcFiles(serverDir)) {
    let src
    try { src = fs.readFileSync(file, 'utf8') }
    catch { continue }
    try {
      const tokens = new Lexer(src, file).tokenize()
      const program = new Parser(tokens, file).parse()
      models.push(...program.declarations.filter(d => d.type === 'ModelDecl'))
    } catch { continue }
  }
  return models
}

// ── Generators ────────────────────────────────────────────────────────────────

function generateAdminRoutes(model) {
  const name = model.name
  const plural = _pluralize(name)

  return `# Generated by arc scaffold ${name} — customize as needed

@route @auth(admin,editor) get "/admin/${plural}" -> Response
  const limit = +(params.limit ?? 20)
  const offset = +(params.offset ?? 0)
  json({ ${plural}: db.${plural}.findMany({ limit, offset }), total: db.${plural}.count() })

@route @auth(admin,editor) get "/admin/${plural}/:id" -> Response
  const item = db.${plural}.find(params.id)
  match item
    None    -> json({ error: "not found" }, 404)
    Some(x) -> json(x)

@route @auth(admin,editor) post "/admin/${plural}" -> Response
  const body = parseBody(request)
  json(db.${plural}.create(body), 201)

@route @auth(admin,editor) patch "/admin/${plural}/:id" -> Response
  const body = parseBody(request)
  json(db.${plural}.update(params.id, body))

@route @auth(admin) del "/admin/${plural}/:id" -> Response
  db.${plural}.delete(params.id)
  json({ ok: true })
`
}

function generateListPage(model) {
  const name = model.name
  const plural = _pluralize(name)

  const listFields = _editableFields(model)
    .filter(f => f.name !== 'createdAt' && f.name !== 'updatedAt')
    .slice(0, 4)

  const headers = listFields.map(f =>
    `            th "${f.name.replace(/([A-Z])/g, ' $1').trim()}"`
  ).join('\n')

  const cells = listFields.map(f => `            td "{item.${f.name}}"`).join('\n')

  return `page "${name}s — Admin"

  @server fn list${name}s() -> Any
    return { items: db.${plural}.findMany({ limit: 50 }), total: db.${plural}.count() }

  @live const data = list${name}s()

  row class="topnav" justify="space-between" align="center" p="0 20px"
    row align="center" gap="10px"
      text class="nav-logo" "◈"
      text class="nav-brand" "${name}s"
    link href="/admin/${plural}/new"
      button class="btn-primary" "+ New ${name}"

  col p="24px" gap="20px"
    col class="card"
      table class="data-table"
        thead
          tr
            th "ID"
${headers}
            th ""
        for item in data.items
          tr class="data-row"
            td class="cell-mono" "#{item.id}"
${cells}
            td class="cell-actions"
              link href="/admin/${plural}/{item.id}/edit"
                button class="btn-ghost" "Edit"

  design
    :root
      --bg: #ffffff
      --bg-2: #f5f5f5
      --bg-3: #efefef
      --fg: #0a0a0a
      --fg-2: #525252
      --fg-3: #a3a3a3
      --border: #e5e5e5
      --invert-bg: #0a0a0a
      --invert-fg: #ffffff
      @dark
        --bg: #0d0d0d
        --bg-2: #161616
        --bg-3: #1f1f1f
        --fg: #f0f0f0
        --fg-2: rgba(255,255,255,0.55)
        --fg-3: rgba(255,255,255,0.28)
        --border: rgba(255,255,255,0.08)
        --invert-bg: #ffffff
        --invert-fg: #0a0a0a
    body
      background-color: var(--bg)
      color: var(--fg)
      font: system-ui, -apple-system, sans-serif
      m: 0
      size: 14px
    .topnav
      height: 52px
      background-color: var(--bg-2)
      border-bottom: 1px solid var(--border)
      flex-shrink: 0
    .nav-logo
      size: 18px
      weight: 700
    .nav-brand
      size: 15px
      weight: 600
      letter-spacing: -0.01em
    .card
      background-color: var(--bg-2)
      border: 1px solid var(--border)
      radius: 14px
      overflow: hidden
      box-shadow: 0 1px 3px rgba(0,0,0,0.05)
      @dark
        box-shadow: 0 1px 3px rgba(0,0,0,0.35)
    .data-table
      w: 100%
      border-collapse: collapse
    thead th
      p: 10px 16px
      size: 11px
      weight: 600
      text-transform: uppercase
      letter-spacing: 0.07em
      color: var(--fg-3)
      text-align: left
      border-bottom: 1px solid var(--border)
    .data-row
      border-bottom: 1px solid var(--border)
      transition: background-color 0.1s
    .data-row:last-child
      border-bottom: none
    .data-row:hover
      background-color: var(--bg-3)
    td
      p: 11px 16px
      color: var(--fg)
    .cell-mono
      color: var(--fg-3)
      size: 12px
      font-family: ui-monospace, "SF Mono", monospace
    .cell-actions
      text-align: right
    .btn-primary
      p: 7px 14px
      background-color: var(--invert-bg)
      color: var(--invert-fg)
      border: none
      radius: 8px
      size: 13px
      weight: 600
      cursor: pointer
    .btn-ghost
      p: 5px 11px
      background-color: transparent
      color: var(--fg-2)
      border: 1px solid var(--border)
      radius: 7px
      size: 12px
      weight: 500
      cursor: pointer
    .btn-ghost:hover
      background-color: var(--bg-3)
      color: var(--fg)
`
}

function generateFormPage(model) {
  const name = model.name
  const plural = _pluralize(name)

  const skipFields = new Set(['createdAt', 'updatedAt', 'oauthId', 'oauthProvider', 'passwordHash'])
  const fields = _editableFields(model).filter(f => !skipFields.has(f.name))

  const formInputs = fields.map(f => {
    const inputType = _fieldToInputType(f)
    const label = f.name.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase())
    const optional = f.typeAnnotation?.nullable === true || f.optional === true
    if (inputType === 'checkbox') {
      return `          row class="checkbox-row" gap="8px" align="center"
            input type="checkbox" name="${f.name}"
            text class="checkbox-text" "${label}"`
    }
    return `          col gap="6px"
            text class="field-label" "${label}${optional ? '' : ' *'}"
            input type="${inputType}" name="${f.name}"${optional ? '' : ' required'}`
  }).join('\n')

  return `page "New ${name} — Admin"

  row class="topnav" justify="space-between" align="center" p="0 20px"
    row align="center" gap="10px"
      text class="nav-logo" "◈"
      link href="/admin/${plural}" class="back-link" "← ${name}s"
    text class="nav-title" "New ${name}"

  col p="24px"
    col class="card form-card" max-w="600px"
      form method="post" action="/admin/${plural}"
        col gap="20px" p="24px"
${formInputs}
          row justify="flex-end" gap="10px"
            link href="/admin/${plural}"
              button type="button" class="btn-cancel" "Cancel"
            button type="submit" class="btn-submit" "Create ${name}"

  design
    :root
      --bg: #ffffff
      --bg-2: #f5f5f5
      --bg-3: #efefef
      --fg: #0a0a0a
      --fg-2: #525252
      --fg-3: #a3a3a3
      --border: #e5e5e5
      --invert-bg: #0a0a0a
      --invert-fg: #ffffff
      @dark
        --bg: #0d0d0d
        --bg-2: #161616
        --bg-3: #1f1f1f
        --fg: #f0f0f0
        --fg-2: rgba(255,255,255,0.55)
        --fg-3: rgba(255,255,255,0.28)
        --border: rgba(255,255,255,0.08)
        --invert-bg: #ffffff
        --invert-fg: #0a0a0a
    body
      background-color: var(--bg)
      color: var(--fg)
      font: system-ui, -apple-system, sans-serif
      m: 0
      size: 14px
    .topnav
      height: 52px
      background-color: var(--bg-2)
      border-bottom: 1px solid var(--border)
      flex-shrink: 0
    .nav-logo
      size: 18px
      weight: 700
    .nav-title
      size: 14px
      weight: 600
      letter-spacing: -0.01em
    .back-link
      color: var(--fg-3)
      size: 13px
      text-decoration: none
    .back-link:hover
      color: var(--fg)
    .card
      background-color: var(--bg-2)
      border: 1px solid var(--border)
      radius: 14px
      overflow: hidden
      box-shadow: 0 1px 3px rgba(0,0,0,0.05)
      @dark
        box-shadow: 0 1px 3px rgba(0,0,0,0.35)
    .field-label
      size: 11px
      weight: 600
      text-transform: uppercase
      letter-spacing: 0.06em
      color: var(--fg-3)
    input
      background-color: var(--bg-3)
      border: 1px solid var(--border)
      color: var(--fg)
      radius: 10px
      p: 10px 14px
      w: 100%
      size: 14px
      outline: none
    input:focus
      border-color: var(--fg-2)
    .checkbox-row
      cursor: pointer
    .checkbox-text
      size: 14px
      color: var(--fg-2)
    .btn-submit
      p: 9px 20px
      background-color: var(--invert-bg)
      color: var(--invert-fg)
      border: none
      radius: 9px
      size: 14px
      weight: 600
      cursor: pointer
    .btn-cancel
      p: 9px 20px
      background-color: transparent
      color: var(--fg-2)
      border: 1px solid var(--border)
      radius: 9px
      size: 14px
      weight: 500
      cursor: pointer
    .btn-cancel:hover
      background-color: var(--bg-3)
      color: var(--fg)
`
}

// ── Main entry ────────────────────────────────────────────────────────────────

async function scaffold(modelName, projectDir, opts = {}) {
  if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(modelName)) {
    console.error(`arc scaffold: invalid model name "${modelName}" — use letters, numbers, underscores starting with a letter`)
    process.exit(1)
  }
  const absDir = path.resolve(projectDir)
  const _t0 = Date.now()

  const model = _findModel(modelName, absDir)
  if (!model) {
    console.error(`arc scaffold: model "${modelName}" not found in ${path.relative(process.cwd(), absDir)}`)
    console.error(`  Define it in server/schemas/${modelName.toLowerCase()}.arc first`)
    process.exit(1)
  }

  const name = model.name
  const plural = _pluralize(name)
  const routesFile = path.join(absDir, 'server', 'admin', 'routes', `${plural}.arc`)
  const listFile   = path.join(absDir, 'admin', `${plural}.arc`)
  const formFile   = path.join(absDir, 'admin', `${name.toLowerCase()}-form.arc`)

  const existing = [routesFile, listFile, formFile].filter(f => fs.existsSync(f))
  if (existing.length > 0 && !opts.force) {
    for (const f of existing) {
      console.error(`arc scaffold: ${path.relative(process.cwd(), f)} already exists (--force to overwrite)`)
    }
    process.exit(1)
  }

  fs.mkdirSync(path.dirname(routesFile), { recursive: true })
  fs.mkdirSync(path.dirname(listFile), { recursive: true })

  fs.writeFileSync(routesFile, generateAdminRoutes(model))
  fs.writeFileSync(listFile, generateListPage(model))
  fs.writeFileSync(formFile, generateFormPage(model))

  const elapsed = Date.now() - _t0
  const rRel = path.relative(process.cwd(), routesFile)
  const lRel = path.relative(process.cwd(), listFile)
  const fRel = path.relative(process.cwd(), formFile)

  if (_C) {
    console.log(`\n  ${_CYAN}⚡ arc scaffold${_RST} ${name}  →  server/ + admin/\n`)
    console.log(`  ${_DIM}routes${_RST}  ${rRel}    ${_DIM}(5 routes)${_RST}`)
    console.log(`  ${_DIM}page  ${_RST}  ${lRel}   ${_DIM}(list · pagination)${_RST}`)
    console.log(`  ${_DIM}page  ${_RST}  ${fRel}   ${_DIM}(create form)${_RST}`)
    console.log(`\n  ${_GREEN}✓${_RST}  scaffold complete in ${_DIM}${elapsed}ms${_RST}`)
    console.log(`  ${_DIM}↳  arc build-server . && arc build-site admin/${_RST}\n`)
  } else {
    console.log(`arc scaffold: created ${rRel}`)
    console.log(`arc scaffold: created ${lRel}`)
    console.log(`arc scaffold: created ${fRel}`)
  }
}

async function scaffoldAll(projectDir, opts = {}) {
  const absDir = path.resolve(projectDir)
  const models = _findAllModels(absDir)
  if (models.length === 0) {
    console.error(`arc scaffold: no model declarations found in ${path.relative(process.cwd(), absDir)}`)
    process.exit(1)
  }
  for (const model of models) {
    await scaffold(model.name, projectDir, opts)
  }
}

// ── Block generators ──────────────────────────────────────────────────────────

const _BLOCK_CSS = `
    :root
      --bg: #ffffff
      --bg-2: #f5f5f5
      --bg-3: #efefef
      --fg: #0a0a0a
      --fg-2: #525252
      --fg-3: #a3a3a3
      --border: #e5e5e5
      --invert-bg: #0a0a0a
      --invert-fg: #ffffff
      @dark
        --bg: #0d0d0d
        --bg-2: #161616
        --bg-3: #1f1f1f
        --fg: #f0f0f0
        --fg-2: rgba(255,255,255,0.55)
        --fg-3: rgba(255,255,255,0.28)
        --border: rgba(255,255,255,0.08)
        --invert-bg: #ffffff
        --invert-fg: #0a0a0a
    body
      background-color: var(--bg)
      color: var(--fg)
      font: system-ui, -apple-system, sans-serif
      m: 0
      size: 14px
    .topnav
      height: 52px
      background-color: var(--bg-2)
      border-bottom: 1px solid var(--border)
      flex-shrink: 0
    .nav-logo
      size: 18px
      weight: 700
    .back-link
      color: var(--fg-3)
      size: 13px
      text-decoration: none
    .back-link:hover
      color: var(--fg)
    .card
      background-color: var(--bg-2)
      border: 1px solid var(--border)
      radius: 14px
      overflow: hidden
      box-shadow: 0 1px 3px rgba(0,0,0,0.05)
      @dark
        box-shadow: 0 1px 3px rgba(0,0,0,0.35)
    .field-label
      size: 11px
      weight: 600
      text-transform: uppercase
      letter-spacing: 0.06em
      color: var(--fg-3)
    input, textarea
      background-color: var(--bg-3)
      border: 1px solid var(--border)
      color: var(--fg)
      radius: 10px
      p: 10px 14px
      w: 100%
      size: 14px
      outline: none
      font: inherit
    textarea
      resize: vertical
      min-height: 100px
    input:focus, textarea:focus
      border-color: var(--fg-2)
    .btn-submit
      p: 9px 20px
      background-color: var(--invert-bg)
      color: var(--invert-fg)
      border: none
      radius: 9px
      size: 14px
      weight: 600
      cursor: pointer
    .btn-cancel
      p: 9px 20px
      background-color: transparent
      color: var(--fg-2)
      border: 1px solid var(--border)
      radius: 9px
      size: 14px
      weight: 500
      cursor: pointer
    .btn-cancel:hover
      background-color: var(--bg-3)
      color: var(--fg)`

function generateBlockEditorPage(type, fields) {
  const label = type.charAt(0).toUpperCase() + type.slice(1)
  const formInputs = fields.map(f => {
    const lbl = f.name.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase())
    if (f.type === 'Bool') {
      return `          row class="checkbox-row" gap="8px" align="center"
            input type="checkbox" name="${f.name}"
            text class="field-label" "${lbl}"`
    }
    const tag = f.type === 'Text' ? 'textarea' : 'input'
    const attrs = tag === 'input' ? ` type="text"` : ''
    return `          col gap="6px"
            text class="field-label" "${lbl}${f.optional ? '' : ' *'}"
            ${tag}${attrs} name="${f.name}"${f.optional ? '' : ' required'} ""`
  }).join('\n')

  return `page "${label} Block — Editor"

  @server fn getBlock() -> Any
    const id = +(params.id ?? 0)
    if id > 0
      return { block: db.pageblocks.find(id) }
    return { block: null }

  @live const data = getBlock()

  row class="topnav" justify="space-between" align="center" p="0 20px"
    row align="center" gap="10px"
      text class="nav-logo" "◈"
      link href="/admin/blocks" class="back-link" "← Blocks"
    text class="nav-title" "${label} Block"

  col p="24px"
    col class="card form-card" max-w="600px"
      form method="post" action="/admin/blocks/{data.block.id}"
        col gap="20px" p="24px"
${formInputs}
          row justify="flex-end" gap="10px"
            link href="/admin/blocks"
              button type="button" class="btn-cancel" "Cancel"
            button type="submit" class="btn-submit" "Save Block"

  design${_BLOCK_CSS}
    .nav-title
      size: 14px
      weight: 600
`
}

function generateBlockWidget(type, fields) {
  const widgetName = type.charAt(0).toUpperCase() + type.slice(1) + 'Block'
  const paramList = ['id: Int', 'type: String', ...fields.map(f => `${f.name}: ${f.type}${f.optional ? '?' : ''}`)]
  const elLines = fields.map(f => {
    if (f.type === 'Bool') {
      return `    if ${f.name}\n      col data-field="${f.name}" "✓"`
    }
    if (f.type === 'Text') {
      return `    text class="block-${type}-${f.name}" data-field="${f.name}" "{${f.name}}"`
    }
    return `    heading class="block-${type}-${f.name}" data-field="${f.name}" "{${f.name}}"`
  }).join('\n')

  return `widget ${widgetName}(${paramList.join(', ')})
  col class="block-${type}" data-block-id="{id}" data-block-type="{type}"
${elLines}
`
}

function generateBlocksAdminPage() {
  return `page "Blocks — Admin"

  @server fn loadBlocks() -> Any
    return {
      blocks: db.pageblocks.findMany({ orderBy: { order: "asc" } }),
      types: db.blockTypes()
    }

  @live const data = loadBlocks()
  @state let selectedPage = "home"

  row class="topnav" justify="space-between" align="center" p="0 20px"
    row align="center" gap="10px"
      text class="nav-logo" "◈"
      text class="nav-brand" "Blocks"
    row gap="8px"
      select aria-label="Select page" onchange="@selectedPage = this.value" class="page-select"
        option value="home" "Home"
        option value="about" "About"

  col p="24px" gap="20px"
    col class="card"
      table class="data-table"
        thead
          tr
            th "Order"
            th "Type"
            th "Page"
            th "Visible"
            th ""
        for block in data.blocks
          tr class="data-row"
            td class="cell-mono" "#{block.order}"
            td "{block.type}"
            td class="cell-mono" "{block.page}"
            td "{block.visible}"
            td class="cell-actions"
              link href="/admin/blocks/{block.type}?id={block.id}"
                button class="btn-ghost" "Edit"

  design
    :root
      --bg: #ffffff
      --bg-2: #f5f5f5
      --bg-3: #efefef
      --fg: #0a0a0a
      --fg-2: #525252
      --fg-3: #a3a3a3
      --border: #e5e5e5
      --invert-bg: #0a0a0a
      --invert-fg: #ffffff
      @dark
        --bg: #0d0d0d
        --bg-2: #161616
        --bg-3: #1f1f1f
        --fg: #f0f0f0
        --fg-2: rgba(255,255,255,0.55)
        --fg-3: rgba(255,255,255,0.28)
        --border: rgba(255,255,255,0.08)
        --invert-bg: #ffffff
        --invert-fg: #0a0a0a
    body
      background-color: var(--bg)
      color: var(--fg)
      font: system-ui, -apple-system, sans-serif
      m: 0
      size: 14px
    .topnav
      height: 52px
      background-color: var(--bg-2)
      border-bottom: 1px solid var(--border)
      flex-shrink: 0
    .nav-logo
      size: 18px
      weight: 700
    .nav-brand
      size: 15px
      weight: 600
    .page-select
      background-color: var(--bg-3)
      border: 1px solid var(--border)
      color: var(--fg)
      radius: 8px
      p: 6px 12px
      size: 13px
    .card
      background-color: var(--bg-2)
      border: 1px solid var(--border)
      radius: 14px
      overflow: hidden
    .data-table
      w: 100%
      border-collapse: collapse
    thead th
      p: 10px 16px
      size: 11px
      weight: 600
      text-transform: uppercase
      letter-spacing: 0.07em
      color: var(--fg-3)
      text-align: left
      border-bottom: 1px solid var(--border)
    .data-row
      border-bottom: 1px solid var(--border)
    .data-row:last-child
      border-bottom: none
    .data-row:hover
      background-color: var(--bg-3)
    td
      p: 11px 16px
      color: var(--fg)
    .cell-mono
      color: var(--fg-3)
      size: 12px
      font-family: ui-monospace, "SF Mono", monospace
    .cell-actions
      text-align: right
    .btn-ghost
      p: 5px 11px
      background-color: transparent
      color: var(--fg-2)
      border: 1px solid var(--border)
      radius: 7px
      size: 12px
      cursor: pointer
    .btn-ghost:hover
      background-color: var(--bg-3)
      color: var(--fg)
`
}

// ── Block scaffold entry points ───────────────────────────────────────────────

async function scaffoldBlockInit(projectDir) {
  const absDir = path.resolve(projectDir)
  const draftSrc = path.join(__dirname, '..', 'draft', 'arc-draft.js')

  const files = {
    [path.join(absDir, 'server', 'schemas', 'pageblock.arc')]: `model PageBlock
  @id let id       = autoincrement()
  let page         : String
  let type         : String
  let order        : Int = 0
  let visible      : Bool = true
  let data         : String = "{}"
  let updatedAt    : DateTime = now()

model DraftToken
  @id let id       = autoincrement()
  let token        : String
  let expiresAt    : DateTime
`,
    [path.join(absDir, 'server', 'admin', 'routes', 'blocks.arc')]: `# Block CRUD + draft token routes

@route @auth(admin,editor) get "/admin/blocks" -> Response
  const pageSlug = params.page ?? "home"
  json({ blocks: db.pageblocks.findMany({ where: { page: pageSlug }, orderBy: { order: "asc" } }) })

@route @auth(admin,editor) post "/admin/blocks" -> Response
  const body = parseBody(request)
  const maxOrder = db.pageblocks.count({ where: { page: body.page } })
  json(db.pageblocks.create({ ...body, order: maxOrder }), 201)

@route @auth(admin,editor) patch "/admin/blocks/:id" -> Response
  const body = parseBody(request)
  const block = db.pageblocks.find(params.id)
  match block
    None    -> json({ error: "not found" }, 404)
    Some(b) ->
      const merged = JSON.parse(b.data)
      for key, val in body.data
        merged[key] = val
      json(db.pageblocks.update(params.id, { data: JSON.stringify(merged), updatedAt: now() }))

@route @auth(admin,editor) patch "/admin/blocks/:id/reorder" -> Response
  const body = parseBody(request)
  const block = db.pageblocks.find(params.id)
  match block
    None    -> json({ error: "not found" }, 404)
    Some(b) ->
      const dir = body.direction
      const neighbor = dir == "up"
        ? db.pageblocks.findFirst({ where: { page: b.page, order: { lt: b.order } }, orderBy: { order: "desc" } })
        : db.pageblocks.findFirst({ where: { page: b.page, order: { gt: b.order } }, orderBy: { order: "asc" } })
      match neighbor
        None    -> json({ ok: false })
        Some(n) ->
          db.pageblocks.update(params.id, { order: n.order })
          db.pageblocks.update(n.id, { order: b.order })
          json({ ok: true })

@route @auth(admin) del "/admin/blocks/:id" -> Response
  db.pageblocks.delete(params.id)
  json({ ok: true })

@route @auth(admin,editor) get "/admin/api/block-types" -> Response
  json(loadBlockTypes())

@route @auth(admin,editor) post "/admin/api/draft-token" -> Response
  const raw = crypto.randomBytes(32).toString("hex")
  const expires = new Date(Date.now() + 8 * 3600 * 1000)
  db.drafttokens.create({ token: raw, expiresAt: expires })
  json({ token: raw })

@route get "/admin/api/draft" -> Response
  const token = params.token ?? ""
  const row = db.drafttokens.findFirst({ where: { token } })
  match row
    None    -> json({ valid: false })
    Some(t) -> json({ valid: new Date(t.expiresAt) > new Date() })

@route @auth(admin,editor) post "/admin/api/publish" -> Response
  json({ ok: true, publishedAt: now() })
`,
    [path.join(absDir, 'server', 'block-types.json')]: '{}',
    [path.join(absDir, 'admin', 'blocks.arc')]: generateBlocksAdminPage(),
  }

  const existing = Object.keys(files).filter(f => fs.existsSync(f))
  if (existing.length > 0) {
    for (const f of existing) console.error(`arc scaffold block --init: ${path.relative(process.cwd(), f)} already exists`)
    process.exit(1)
  }

  for (const [dest, content] of Object.entries(files)) {
    fs.mkdirSync(path.dirname(dest), { recursive: true })
    fs.writeFileSync(dest, content)
  }

  // Copy draft script to public/
  const publicDraft = path.join(absDir, 'public', 'arc-draft.js')
  fs.mkdirSync(path.dirname(publicDraft), { recursive: true })
  if (fs.existsSync(draftSrc)) {
    fs.copyFileSync(draftSrc, publicDraft)
  }

  if (_C) {
    console.log(`\n  ${_CYAN}⚡ arc scaffold block --init${_RST}\n`)
    for (const f of [...Object.keys(files), publicDraft]) {
      console.log(`  ${_GREEN}+${_RST} ${path.relative(process.cwd(), f)}`)
    }
    console.log(`\n  ${_DIM}↳  next: arc scaffold block <Type> --fields "title:String body:Text"${_RST}\n`)
  } else {
    for (const f of Object.keys(files)) console.log(`arc scaffold block --init: created ${path.relative(process.cwd(), f)}`)
  }
}

async function scaffoldBlock(type, projectDir, opts = {}) {
  const absDir = path.resolve(projectDir)
  const typesFile = path.join(absDir, 'server', 'block-types.json')

  if (!fs.existsSync(typesFile)) {
    console.error(`arc scaffold block: server/block-types.json not found — run arc scaffold block --init first`)
    process.exit(1)
  }

  const typeKey = type.toLowerCase()
  if (!/^[a-z][a-z0-9_-]*$/.test(typeKey)) {
    console.error(`arc scaffold block: invalid block type name "${type}" — use lowercase letters, numbers, hyphens, underscores`)
    process.exit(1)
  }
  const fields = _parseFieldsArg(opts.fields)

  // Update block-types.json — use a lock file to prevent concurrent write races
  const lockFile = typesFile + '.lock'
  let lockAcquired = false
  try {
    fs.writeFileSync(lockFile, String(process.pid), { flag: 'wx' })
    lockAcquired = true
  } catch (e) {
    if (e.code === 'EEXIST') {
      console.error(`arc scaffold block: another scaffold is running — remove ${path.relative(process.cwd(), lockFile)} if stale`)
      process.exit(1)
    }
    throw e
  }
  // Release lock on unexpected exit (SIGINT/SIGTERM or unhandled error)
  const _lockRelease = () => { if (!lockAcquired) return; lockAcquired = false; try { fs.unlinkSync(lockFile) } catch {} }
  process.once('exit', _lockRelease)
  process.once('SIGINT', () => { _lockRelease(); process.exit(130) })
  process.once('SIGTERM', () => { _lockRelease(); process.exit(143) })
  let registry
  try {
    registry = JSON.parse(fs.readFileSync(typesFile, 'utf8'))
  } catch (e) {
    console.error(`arc scaffold block: invalid JSON in server/block-types.json: ${e.message}`)
    fs.unlinkSync(lockFile)
    process.exit(1)
  }
  if (registry[typeKey] && !opts.force) {
    console.error(`arc scaffold block: block type "${typeKey}" already exists (--force to overwrite)`)
    fs.unlinkSync(lockFile)
    process.exit(1)
  }
  registry[typeKey] = {
    label: type.charAt(0).toUpperCase() + type.slice(1).replace(/([A-Z])/g, ' $1').trim(),
    fields: fields.map(f => ({ name: f.name, type: f.type, label: f.name.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase()), ...(f.optional ? { optional: true } : {}) }))
  }
  try {
    fs.writeFileSync(typesFile, JSON.stringify(registry, null, 2))
  } catch (e) {
    lockAcquired = false
    fs.unlinkSync(lockFile)
    console.error(`arc scaffold block: failed to write ${path.relative(process.cwd(), typesFile)}: ${e.message}`)
    process.exit(1)
  }
  lockAcquired = false
  fs.unlinkSync(lockFile)

  const editorFile = path.join(absDir, 'admin', 'blocks', `${typeKey}.arc`)
  const widgetFile = path.join(absDir, 'site', 'blocks', `${typeKey}.arc`)

  try {
    fs.mkdirSync(path.dirname(editorFile), { recursive: true })
    fs.mkdirSync(path.dirname(widgetFile), { recursive: true })
    fs.writeFileSync(editorFile, generateBlockEditorPage(typeKey, fields))
    fs.writeFileSync(widgetFile, generateBlockWidget(typeKey, fields))
  } catch (e) {
    console.error(`arc scaffold block: failed to write generated files: ${e.message}`)
    process.exit(1)
  }

  if (_C) {
    console.log(`\n  ${_CYAN}⚡ arc scaffold block${_RST} ${type}\n`)
    console.log(`  ${_GREEN}~${_RST} ${path.relative(process.cwd(), typesFile)}   (updated)`)
    console.log(`  ${_GREEN}+${_RST} ${path.relative(process.cwd(), editorFile)}`)
    console.log(`  ${_GREEN}+${_RST} ${path.relative(process.cwd(), widgetFile)}`)
    console.log(`\n  ${_DIM}widget: <${type.charAt(0).toUpperCase() + type.slice(1)}Block id=... type="${typeKey}" ...fields />`)
    console.log(`  ↳  add data-block-id and data-field attrs to your page for draft mode${_RST}\n`)
  } else {
    console.log(`arc scaffold block: updated ${path.relative(process.cwd(), typesFile)}`)
    console.log(`arc scaffold block: created ${path.relative(process.cwd(), editorFile)}`)
    console.log(`arc scaffold block: created ${path.relative(process.cwd(), widgetFile)}`)
  }
}

module.exports = { scaffold, scaffoldAll, scaffoldBlock, scaffoldBlockInit, generateAdminRoutes, generateListPage, generateFormPage, generateBlockWidget, generateBlockEditorPage, _pluralize, _parseFieldsArg }
