'use strict'

// @realtime client generator.
// Produces browser-side code that:
//   1. Opens a WebSocket or SSE connection to the channel
//   2. Receives ADP binary frames
//   3. Directly updates DOM nodes that depend on the realtime variable
//
// Zero connection management code needed in Arc source.

class RealtimeEmitter {
  constructor(options = {}) {
    this.hash = options.hash ?? 'arc'
  }

  // Generate realtime connection code for all @realtime declarations.
  // stateBindings: [{ id, expr }] from HtmlEmitter — to know which DOM nodes to update
  emitAll(realtimeDecls, stateBindings) {
    if (realtimeDecls.length === 0) return ''

    const parts = [
      `// @realtime connections — auto-generated by Arc`,
      `(function() {`,
      `  function _rt_decode(buf) {`,
      `    // Reuse ADP decode if available, else JSON fallback`,
      `    if (typeof _adpDecode === 'function') return _adpDecode(new Uint8Array(buf))`,
      `    return JSON.parse(new TextDecoder().decode(buf))`,
      `  }`,
      ``,
    ]

    for (const decl of realtimeDecls) {
      parts.push(this.emitChannel(decl, stateBindings))
    }

    parts.push(`})()`)
    return parts.join('\n')
  }

  emitChannel(decl, stateBindings) {
    const varName = decl.name
    if (!/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(varName)) {
      throw new Error(`Arc codegen: unsafe @realtime variable name: ${JSON.stringify(varName)}`)
    }
    // Channel expression: channel("chat/{roomId}") → extract the string
    const channelExpr = this.extractChannelName(decl.channel)

    // Trigger reactive setters for @state vars bound to this realtime variable.
    // The setter machinery handles all DOM updates — we just need to assign the new value.
    const escapedName = varName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const re = new RegExp(`\\b${escapedName}\\b`)
    // Single pass: collect setter names and direct-DOM fallback bindings
    const setterNames = new Set()
    const directBindings = []
    for (const b of stateBindings) {
      if (!re.test(b.expr ?? '')) continue
      if (b.stateVar) setterNames.add(b.stateVar)
      else directBindings.push(b)
    }

    const domUpdates = [
      ...[...setterNames].map(sv =>
        `      if (typeof _set_${sv} === 'function') _set_${sv}(${varName})`
      ),
      ...directBindings.map(b => {
        const id = b.id
        return `      const _el_${id} = document.getElementById('${id}'); if (_el_${id}) _el_${id}.textContent = String(${varName} ?? '')`
      }),
    ].join('\n')

    const protocol = `location.protocol === 'https:' ? 'wss:' : 'ws:'`

    return [
      `  // @realtime ${varName} = channel(${channelExpr})`,
      `  let ${varName} = null`,
      `  let _retries_${varName} = 0`,
      `  ;(function _connect_${varName}() {`,
      `    const _url = \`\${${protocol}}//\${location.host}/_arc/rt/\${${channelExpr}}\``,
      `    const _ws = new WebSocket(_url)`,
      `    _ws.binaryType = 'arraybuffer'`,
      `    _ws.onopen = function() { _retries_${varName} = 0 }`,
      `    _ws.onmessage = function(e) {`,
      `      try {`,
      `        ${varName} = _rt_decode(e.data)`,
      `        // Update DOM nodes that depend on ${varName}`,
      `${domUpdates || '        // No DOM bindings found'}`,
      `      } catch(_e) { console.warn('arc realtime:', _e) }`,
      `    }`,
      `    _ws.onclose = function() {`,
      `      // Auto-reconnect with exponential backoff`,
      `      setTimeout(_connect_${varName}, Math.min(1000 * Math.pow(2, Math.min(_retries_${varName}++, 5)), 30000))`,
      `    }`,
      `    _ws.onerror = function(e) { console.warn('arc realtime ws error:', e) }`,
      `  })()`,
      ``,
    ].join('\n')
  }

  extractChannelName(channelExpr) {
    // channel("chat") → "chat"
    // channel("feed/{userId}") → `feed/${userId}`
    if (!channelExpr) return '"unknown"'
    if (channelExpr.type === 'CallExpr') {
      const arg = channelExpr.args?.[0]
      if (arg?.type === 'Literal') return JSON.stringify(arg.value)
      if (arg?.type === 'TemplateLiteral') {
        // Convert Arc template literal to JS template literal
        const parts = arg.parts.map(p => {
          if (p.type === 'Literal') return p.value
          if (p.type === 'Identifier' && /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(p.name)) return `\${${p.name}}`
          return `\${''}` // safe fallback for complex expressions
        })
        return '`' + parts.join('') + '`'
      }
    }
    return '"channel"'
  }
}

module.exports = { RealtimeEmitter }
