'use strict'

function generate({ html = '', css = '', js = '', edgeFunctions = '', projectName = 'arc-app' }) {
  const assets = { '/': html }
  if (css) assets['/styles.css'] = css
  if (js) assets['/app.js'] = js

  const assetsEntries = Object.entries(assets)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n')

  const handlerNames = edgeFunctions
    ? [...new Set((edgeFunctions.match(/function (_handler_\w+)/g) ?? []).map(m => m.slice('function '.length)))]
    : []
  const handlerMapEntries = handlerNames.map(h => `  '${h.slice('_handler_'.length)}': ${h}`).join(',\n')

  const edgeFunctionsBlock = edgeFunctions
    ? `
// Edge functions (from @server declarations)
${edgeFunctions}

const _ARC_HANDLERS = Object.assign(Object.create(null), {
${handlerMapEntries}
})

async function handleEdgeFunction(path, req) {
  const segment = path.slice('/_arc/fn/'.length)
  if (segment.includes('/')) return new Response('Not Found', { status: 404 })
  if (!Object.prototype.hasOwnProperty.call(_ARC_HANDLERS, segment)) return new Response('Edge function not found', { status: 404 })
  const fn = _ARC_HANDLERS[segment]
  if (typeof fn !== 'function') return new Response('Edge function not found', { status: 404 })
  return await fn(req)
}
`
    : ''

  const edgeRoutingBlock = edgeFunctions
    ? `
    if (path.startsWith('/_arc/fn/')) {
      return await handleEdgeFunction(path, req)
    }
`
    : ''

  const server = `// Bun server — generated by Arc
// Run with: bun run server.js

const ASSETS = {
${assetsEntries}
}

function getContentType(path) {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8'
  if (path.endsWith('.css')) return 'text/css'
  if (path.endsWith('.js')) return 'application/javascript'
  if (path.endsWith('.json')) return 'application/json'
  if (path.endsWith('.svg')) return 'image/svg+xml'
  if (path.endsWith('.png')) return 'image/png'
  if (path.endsWith('.ico')) return 'image/x-icon'
  return 'application/octet-stream'
}
${edgeFunctionsBlock}
Bun.serve({
  port: (() => { const p = process.env.PORT ? parseInt(process.env.PORT, 10) : 3000; return (Number.isInteger(p) && p > 0 && p < 65536) ? p : 3000 })(),
  async fetch(req) {
    const url = new URL(req.url)
    let path = url.pathname
    if (path === '' || path === '/') path = '/'
${edgeRoutingBlock}
    const asset = ASSETS[path]
    if (asset !== undefined) {
      return new Response(asset, {
        headers: {
          'Content-Type': getContentType(path),
          'X-Content-Type-Options': 'nosniff',
          'X-Frame-Options': 'SAMEORIGIN',
          'Referrer-Policy': 'strict-origin-when-cross-origin',
        },
      })
    }

    return new Response('Not found', { status: 404 })
  },
})

console.log(\`arc: server running on http://localhost:\${process.env.PORT ?? 3000}\`)
`

  return [
    { path: 'server.js', content: server },
  ]
}

module.exports = { generate }
