'use strict'

const { resolveHandlerNames } = require('./deploy-utils')

function generate({ html = '', css = '', js = '', edgeFunctions = '', handlerNames = null }) {
  const assets = { '/': html }
  if (css) assets['/styles.css'] = css
  if (js) assets['/app.js'] = js

  const assetsEntries = Object.entries(assets)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n')

  const handlerMatches = resolveHandlerNames(handlerNames, edgeFunctions)

  const handlerMapEntries = handlerMatches
    .map(h => `  ${JSON.stringify(h.slice('_handler_'.length))}: ${h}`)
    .join(',\n')

  const edgeFunctionsBlock = edgeFunctions
    ? `
// Edge functions (from @server declarations)
${edgeFunctions}

const _ARC_HANDLERS = Object.assign(Object.create(null), {
${handlerMapEntries}
})

async function handleEdgeFunction(path, req) {
  const segment = path.slice('/_arc/fn/'.length)
  if (segment.includes('/')) return new Response('Not Found', { status: 404 })
  if (!Object.prototype.hasOwnProperty.call(_ARC_HANDLERS, segment)) return new Response('Edge function not found', { status: 404 })
  const fn = _ARC_HANDLERS[segment]
  if (typeof fn !== 'function') return new Response('Edge function not found', { status: 404 })
  const _cLen = parseInt(req.headers.get('content-length') ?? '0', 10)
  if (_cLen > 1048576) return new Response(JSON.stringify({ error: 'Request body too large' }), { status: 413, headers: { 'Content-Type': 'application/json' } })
  try {
    const arcReq = new Request(req.url, { method: req.method, headers: req.headers, body: req.body })
    return await fn(arcReq)
  } catch (e) {
    console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'edge_fn_error', msg: e instanceof Error ? e.message : String(e) }))
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500, headers: { 'Content-Type': 'application/json' } })
  }
}
`
    : ''

  const edgeRoutingBlock = edgeFunctions
    ? `
    if (path.startsWith('/_arc/fn/')) {
      return await handleEdgeFunction(path, req)
    }
`
    : ''

  const server = `// Bun server: generated by Arc
// Run with: bun run server.js

const ASSETS = {
${assetsEntries}
}

function getContentType(path) {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8'
  if (path.endsWith('.css')) return 'text/css'
  if (path.endsWith('.js')) return 'application/javascript'
  if (path.endsWith('.json')) return 'application/json'
  if (path.endsWith('.svg')) return 'image/svg+xml'
  if (path.endsWith('.png')) return 'image/png'
  if (path.endsWith('.ico')) return 'image/x-icon'
  return 'application/octet-stream'
}
${edgeFunctionsBlock}
const _rawPort = process.env.PORT ? parseInt(process.env.PORT, 10) : 3000
const PORT = (Number.isInteger(_rawPort) && _rawPort > 0 && _rawPort < 65536) ? _rawPort : 3000

let _server
try {
  _server = Bun.serve({
    port: PORT,
    idleTimeout: 65,
    async fetch(req) {
      const url = new URL(req.url)
      let path = url.pathname
      if (path === '' || path === '/') path = '/'
      if (path === '/_arc/health') {
        return new Response(JSON.stringify({ status: 'ok', uptime: process.uptime(), ts: new Date().toISOString() }), {
          headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store, no-cache' }
        })
      }
${edgeRoutingBlock}
      const asset = ASSETS[path]
      if (asset !== undefined) {
        return new Response(asset, {
          headers: {
            'Content-Type': getContentType(path),
            'Cache-Control': path === '/' ? 'no-cache' : 'public, max-age=31536000, immutable',
            'Content-Security-Policy': "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; form-action 'self'",
            'X-Content-Type-Options': 'nosniff',
            'X-Frame-Options': 'SAMEORIGIN',
            'Referrer-Policy': 'strict-origin-when-cross-origin',
            'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
            'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
          },
        })
      }

      return new Response('Not found', { status: 404, headers: { 'Content-Type': 'text/plain', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "default-src 'none'", 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Permissions-Policy': 'camera=(), microphone=(), geolocation=()' } })
    },
  })
} catch (e) {
  console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'server_start_failed', msg: e instanceof Error ? e.message : String(e) }))
  process.exit(1)
}
process.stdout.isTTY
  ? console.log(\`arc: server running on http://localhost:\${_server.port}\`)
  : console.log(JSON.stringify({ ts: new Date().toISOString(), level: 'info', event: 'server_start', msg: \`arc: server running on http://localhost:\${_server.port}\` }))
process.on('SIGTERM', () => { _server.stop(true) })
process.on('SIGINT', () => { _server.stop(true) })
`

  return [
    { path: 'server.js', content: server },
  ]
}

module.exports = { generate }
