'use strict'

const { resolveHandlerNames } = require('./deploy-utils')

function generate({ html = '', css = '', js = '', edgeFunctions = '', handlerNames = null }) {
  const assets = { '/': html }
  if (css) assets['/styles.css'] = css
  if (js) assets['/app.js'] = js

  const assetsEntries = Object.entries(assets)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n')

  const handlerMatches = resolveHandlerNames(handlerNames, edgeFunctions)

  const handlerMapEntries = handlerMatches
    .map(h => `  ${JSON.stringify(h.slice('_handler_'.length))}: ${h}`)
    .join(',\n')

  const edgeFunctionsBlock = edgeFunctions
    ? `
// Edge functions (from @server declarations)
${edgeFunctions}

const _ARC_HANDLERS = Object.assign(Object.create(null), {
${handlerMapEntries}
})

async function handleEdgeFunction(path, req) {
  const segment = path.slice('/_arc/fn/'.length)
  if (!segment || !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(segment)) return new Response(JSON.stringify({ error: 'Not found' }), { status: 404, headers: { 'Content-Type': 'application/json' } })
  if (!Object.prototype.hasOwnProperty.call(_ARC_HANDLERS, segment)) return new Response(JSON.stringify({ error: 'Edge function not found' }), { status: 404, headers: { 'Content-Type': 'application/json' } })
  const fn = _ARC_HANDLERS[segment]
  if (typeof fn !== 'function') return new Response(JSON.stringify({ error: 'Edge function not found' }), { status: 404, headers: { 'Content-Type': 'application/json' } })
  try {
    const _hasBody = req.method !== 'GET' && req.method !== 'HEAD'
    const _cl = _hasBody ? +(req.headers.get('content-length') ?? 0) : 0
    if (_cl > 1048576) return new Response(JSON.stringify({ error: 'Request body too large' }), { status: 413, headers: { 'Content-Type': 'application/json' } })
    const _body = _hasBody ? await req.arrayBuffer() : null
    if (_body && _body.byteLength > 1048576) return new Response(JSON.stringify({ error: 'Request body too large' }), { status: 413, headers: { 'Content-Type': 'application/json' } })
    const arcReq = new Request(req.url, { method: req.method, headers: req.headers, ...(_body ? { body: _body } : {}) })
    arcReq._arc_session = req._arc_session ? { ...req._arc_session } : {}
    const _fnRes = await fn(arcReq)
    return _fnRes instanceof Response ? _fnRes : new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500, headers: { 'Content-Type': 'application/json' } })
  } catch (e) {
    console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'edge_fn_error', path, msg: e instanceof Error ? e.message : String(e) }))
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500, headers: { 'Content-Type': 'application/json' } })
  }
}
`
    : ''

  const edgeRoutingBlock = edgeFunctions
    ? `
    if (path.startsWith('/_arc/fn/')) {
      return await handleEdgeFunction(path, req)
    }
`
    : ''

  const server = `// Bun server: generated by Arc
// Run with: bun run server.js

const ASSETS = {
${assetsEntries}
}

const _MIME = { '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'application/javascript', '.json': 'application/json', '.svg': 'image/svg+xml', '.png': 'image/png', '.ico': 'image/x-icon' }
function getContentType(path) {
  const dot = path.lastIndexOf('.')
  return dot !== -1 ? (_MIME[path.slice(dot)] ?? 'application/octet-stream') : 'application/octet-stream'
}
${edgeFunctionsBlock}
const _rawPort = process.env.PORT ? parseInt(process.env.PORT, 10) : 3000
const PORT = (Number.isInteger(_rawPort) && _rawPort > 0 && _rawPort < 65536) ? _rawPort : 3000

let _server
try {
  _server = Bun.serve({
    port: PORT,
    idleTimeout: 65,
    error(err) {
      console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'server_error', msg: err instanceof Error ? err.message : String(err) }))
      return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500, headers: { 'Content-Type': 'application/json' } })
    },
    async fetch(req) {
      try {
        const url = new URL(req.url)
        let path = url.pathname
        if (path === '' || path === '/') path = '/'
        if (path === '/_arc/health') {
          return new Response(JSON.stringify({ status: 'ok', uptime: process.uptime(), queue: 'n/a', version: process.env.npm_package_version ?? 'unknown', ts: new Date().toISOString() }), {
            headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store, no-cache', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY' }
          })
        }
${edgeRoutingBlock}
        const asset = ASSETS[path]
        if (asset !== undefined) {
          return new Response(asset, {
            headers: {
              'Content-Type': getContentType(path),
              'Cache-Control': path === '/' ? 'no-cache' : 'public, max-age=31536000, immutable',
              'Content-Security-Policy': "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; form-action 'self'",
              'X-Content-Type-Options': 'nosniff',
              'X-Frame-Options': 'SAMEORIGIN',
              'Referrer-Policy': 'strict-origin-when-cross-origin',
              'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
              'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
            },
          })
        }

        return new Response('<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found</title></head><body style="font-family:system-ui;padding:2rem"><a href="#main-content" style="position:absolute;left:-9999px;top:auto;overflow:hidden;clip:rect(0,0,0,0)">Skip to main content</a><main id="main-content" style="max-width:40rem;margin:4rem auto"><h1>Page not found</h1><p>The page you requested does not exist.</p><p><a href="/">Return home</a></p></main></body></html>', { status: 404, headers: { 'Content-Type': 'text/html; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "default-src 'self'; style-src 'unsafe-inline'", 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Permissions-Policy': 'camera=(), microphone=(), geolocation=()' } })
      } catch (e) {
        console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'request_error', msg: e instanceof Error ? e.message : String(e) }))
        return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500, headers: { 'Content-Type': 'application/json' } })
      }
    },
  })
} catch (e) {
  console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'server_start_failed', msg: e instanceof Error ? e.message : String(e) }))
  process.exit(1)
}
process.stdout.isTTY
  ? console.log(\`arc: server running on http://localhost:\${_server.port}\`)
  : console.log(JSON.stringify({ ts: new Date().toISOString(), level: 'info', event: 'server_start', msg: \`arc: server running on http://localhost:\${_server.port}\` }))
async function _shutdown(signal) {
  console.log(JSON.stringify({ ts: new Date().toISOString(), level: 'info', event: 'server_shutdown_started', signal }))
  const _t = setTimeout(() => { console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'server_shutdown_timeout', signal })); process.exit(0) }, 5000)
  try { await _server.stop(true) } catch {}
  clearTimeout(_t)
  console.log(JSON.stringify({ ts: new Date().toISOString(), level: 'info', event: 'server_shutdown_complete', signal }))
  process.exit(0)
}
process.on('SIGTERM', () => _shutdown('SIGTERM').catch(() => process.exit(1)))
process.on('SIGINT', () => _shutdown('SIGINT').catch(() => process.exit(1)))
`

  return [
    { path: 'server.js', content: server },
  ]
}

module.exports = { generate }
