'use strict'

function getContentType(p) {
  if (p.endsWith('.html')) return 'text/html; charset=utf-8'
  if (p.endsWith('.css')) return 'text/css'
  if (p.endsWith('.js')) return 'application/javascript'
  if (p.endsWith('.json')) return 'application/json'
  if (p.endsWith('.svg')) return 'image/svg+xml'
  if (p.endsWith('.png')) return 'image/png'
  if (p.endsWith('.ico')) return 'image/x-icon'
  return 'application/octet-stream'
}

const _SAFE_HANDLER_NAME_CF = /^_handler_[a-zA-Z_$][a-zA-Z0-9_$]*$/

function generate({ html = '', css = '', js = '', edgeFunctions = '', projectName = 'arc-app', handlerNames = null }) {
  const assets = { '/': html }
  if (css) assets['/styles.css'] = css
  if (js) assets['/app.js'] = js

  const assetsEntries = Object.entries(assets)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n')

  // Prefer explicit handlerNames from compiler AST; fall back to text scan for deploy-from-files case
  const edgeFnNames = handlerNames
    ? handlerNames.filter(h => _SAFE_HANDLER_NAME_CF.test(h))
    : edgeFunctions
      ? [...edgeFunctions.matchAll(/^async function (_handler_\w+)\s*\(/mg)].map(m => m[1])
          .filter(h => _SAFE_HANDLER_NAME_CF.test(h))
      : []
  const edgeFunctionsBlock = edgeFunctions
    ? `
// Edge functions (from @server declarations)
${edgeFunctions}

const EDGE_FN_MAP = Object.assign(Object.create(null), {${edgeFnNames.map(n => `${n}`).join(',')}})

async function handleEdgeFunction(path, request) {
  const segment = path.slice('/_arc/fn/'.length)
  if (segment.includes('/')) return new Response('Not Found', { status: 404 })
  const key = '_handler_' + segment
  if (!Object.prototype.hasOwnProperty.call(EDGE_FN_MAP, key)) return new Response('Edge function not found', { status: 404 })
  const fn = EDGE_FN_MAP[key]
  if (typeof fn !== 'function') return new Response('Edge function not found', { status: 404 })
  try {
    return await fn(request)
  } catch (e) {
    console.error('[arc] edge function error:', e)
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500, headers: { 'Content-Type': 'application/json' } })
  }
}
`
    : ''

  const edgeRoutingBlock = edgeFunctions
    ? `
    if (path.startsWith('/_arc/fn/')) {
      return await handleEdgeFunction(path, request)
    }
`
    : ''

  const worker = `// Cloudflare Worker — generated by Arc
// Deploy with: npx wrangler deploy

const ASSETS = {
${assetsEntries}
}

function getContentType(path) {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8'
  if (path.endsWith('.css')) return 'text/css'
  if (path.endsWith('.js')) return 'application/javascript'
  if (path.endsWith('.json')) return 'application/json'
  if (path.endsWith('.svg')) return 'image/svg+xml'
  if (path.endsWith('.png')) return 'image/png'
  if (path.endsWith('.ico')) return 'image/x-icon'
  return 'application/octet-stream'
}
${edgeFunctionsBlock}
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    let path = url.pathname
    if (path === '' || path === '/') path = '/'
${edgeRoutingBlock}
    const asset = ASSETS[path]
    if (asset !== undefined) {
      const contentType = getContentType(path)
      return new Response(asset, {
        headers: {
          'Content-Type': contentType,
          'X-Content-Type-Options': 'nosniff',
          'X-Frame-Options': 'SAMEORIGIN',
          'Referrer-Policy': 'strict-origin-when-cross-origin',
        },
      })
    }

    return new Response('Not found', { status: 404 })
  },
}
`

  const wranglerToml = `name = "${projectName}"
main = "worker.js"
compatibility_date = "2024-01-01"

[build]
command = ""
`

  return [
    { path: 'worker.js', content: worker },
    { path: 'wrangler.toml', content: wranglerToml },
  ]
}

module.exports = { generate, getContentType }
