'use strict'

function getContentType(p) {
  if (p.endsWith('.html')) return 'text/html; charset=utf-8'
  if (p.endsWith('.css')) return 'text/css'
  if (p.endsWith('.js')) return 'application/javascript'
  if (p.endsWith('.json')) return 'application/json'
  if (p.endsWith('.svg')) return 'image/svg+xml'
  if (p.endsWith('.png')) return 'image/png'
  if (p.endsWith('.ico')) return 'image/x-icon'
  return 'application/octet-stream'
}

function generate({ html = '', css = '', js = '', edgeFunctions = '', projectName = 'arc-app' }) {
  const assets = { '/': html }
  if (css) assets['/styles.css'] = css
  if (js) assets['/app.js'] = js

  const assetsEntries = Object.entries(assets)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n')

  // Build allowlist from declared @server function names
  const edgeFnNames = edgeFunctions
    ? [...edgeFunctions.matchAll(/^async function (_handler_\w+)\s*\(/mg)].map(m => m[1])
    : []
  const edgeFnNamesLiteral = JSON.stringify(edgeFnNames)

  const edgeFunctionsBlock = edgeFunctions
    ? `
// Edge functions (from @server declarations)
${edgeFunctions}

const EDGE_FN_NAMES = new Set(${edgeFnNamesLiteral})

async function handleEdgeFunction(path, request) {
  const fnName = path.replace('/_arc/fn/', '').replace(/\//g, '_')
  if (!EDGE_FN_NAMES.has(fnName)) {
    return new Response('Edge function not found', { status: 404 })
  }
  if (typeof globalThis[fnName] === 'function') {
    return await globalThis[fnName](request)
  }
  return new Response('Edge function not found', { status: 404 })
}
`
    : ''

  const edgeRoutingBlock = edgeFunctions
    ? `
    if (path.startsWith('/_arc/fn/')) {
      return await handleEdgeFunction(path, request)
    }
`
    : ''

  const worker = `// Cloudflare Worker — generated by Arc
// Deploy with: npx wrangler deploy

const ASSETS = {
${assetsEntries}
}

function getContentType(path) {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8'
  if (path.endsWith('.css')) return 'text/css'
  if (path.endsWith('.js')) return 'application/javascript'
  if (path.endsWith('.json')) return 'application/json'
  if (path.endsWith('.svg')) return 'image/svg+xml'
  if (path.endsWith('.png')) return 'image/png'
  if (path.endsWith('.ico')) return 'image/x-icon'
  return 'application/octet-stream'
}
${edgeFunctionsBlock}
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    let path = url.pathname
    if (path === '' || path === '/') path = '/'
${edgeRoutingBlock}
    const asset = ASSETS[path]
    if (asset !== undefined) {
      const contentType = getContentType(path)
      return new Response(asset, {
        headers: { 'Content-Type': contentType },
      })
    }

    return new Response('Not found', { status: 404 })
  },
}
`

  const wranglerToml = `name = "${projectName}"
main = "worker.js"
compatibility_date = "2024-01-01"

[build]
command = ""
`

  return [
    { path: 'worker.js', content: worker },
    { path: 'wrangler.toml', content: wranglerToml },
  ]
}

module.exports = { generate, getContentType }
