'use strict'

const _SAFE_HANDLER_NAME_DENO = /^_handler_[a-zA-Z_$][a-zA-Z0-9_$]*$/

function generate({ html = '', css = '', js = '', edgeFunctions = '', projectName = 'arc-app', handlerNames = null }) {
  const assets = { '/': html }
  if (css) assets['/styles.css'] = css
  if (js) assets['/app.js'] = js

  const assetsEntries = Object.entries(assets)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n')

  // Prefer explicit handlerNames from compiler AST; fall back to text scan for deploy-from-files case
  const handlerMatches = handlerNames
    ? handlerNames.filter(h => _SAFE_HANDLER_NAME_DENO.test(h))
    : edgeFunctions
      ? [...new Set([...edgeFunctions.matchAll(/^async function (_handler_\w+)\s*\(/mg)].map(m => m[1]))]
          .filter(h => _SAFE_HANDLER_NAME_DENO.test(h))
      : []

  const handlerMapEntries = handlerMatches
    .map(h => `  '${h.slice('_handler_'.length)}': ${h}`)
    .join(',\n')

  const edgeFunctionsBlock = edgeFunctions
    ? `
// Edge functions (from @server declarations)
${edgeFunctions}

const _ARC_HANDLERS: Record<string, (req: Request) => Promise<Response>> = Object.assign(Object.create(null), {
${handlerMapEntries}
})

async function handleEdgeFunction(path: string, req: Request): Promise<Response> {
  const segment = path.slice('/_arc/fn/'.length)
  if (segment.includes('/')) return new Response('Not Found', { status: 404 })
  if (!Object.prototype.hasOwnProperty.call(_ARC_HANDLERS, segment)) return new Response('Edge function not found', { status: 404 })
  const fn = _ARC_HANDLERS[segment]
  if (typeof fn !== 'function') return new Response('Edge function not found', { status: 404 })
  const buf = await req.arrayBuffer()
  if (buf.byteLength > 1048576) return new Response(JSON.stringify({ error: 'Request body too large' }), { status: 413, headers: { 'Content-Type': 'application/json' } })
  try {
    const arcReq = new Request(req.url, { method: req.method, headers: req.headers, body: buf.byteLength > 0 ? buf : null })
    return await fn(arcReq)
  } catch (e) {
    console.error('[arc] edge function error:', e instanceof Error ? e.message : String(e))
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500, headers: { 'Content-Type': 'application/json' } })
  }
}
`
    : ''

  const edgeRoutingBlock = edgeFunctions
    ? `
    if (path.startsWith('/_arc/fn/')) {
      return await handleEdgeFunction(path, req)
    }
`
    : ''

  const server = `// Deno Deploy server — generated by Arc
// Deploy with: deployctl deploy --project=${projectName} server.ts
// Run locally: deno run --allow-net server.ts

import { serve } from "https://deno.land/std@0.208.0/http/server.ts"

const ASSETS: Record<string, string> = {
${assetsEntries}
}

function getContentType(path: string): string {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8'
  if (path.endsWith('.css')) return 'text/css'
  if (path.endsWith('.js')) return 'application/javascript'
  if (path.endsWith('.json')) return 'application/json'
  if (path.endsWith('.svg')) return 'image/svg+xml'
  if (path.endsWith('.png')) return 'image/png'
  if (path.endsWith('.ico')) return 'image/x-icon'
  return 'application/octet-stream'
}
${edgeFunctionsBlock}
serve(async (req: Request): Promise<Response> => {
  const url = new URL(req.url)
  let path = url.pathname
  if (path === '' || path === '/') path = '/'
  if (path === '/_arc/health') {
    return new Response(JSON.stringify({ status: 'ok' }), {
      headers: { 'Content-Type': 'application/json' }
    })
  }
${edgeRoutingBlock}
  const asset = ASSETS[path]
  if (asset !== undefined) {
    return new Response(asset, {
      headers: {
        'Content-Type': getContentType(path),
        'Content-Security-Policy': "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; form-action 'self'",
        'X-Content-Type-Options': 'nosniff',
        'X-Frame-Options': 'SAMEORIGIN',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
        'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
      },
    })
  }

  return new Response('Not found', { status: 404, headers: { 'X-Content-Type-Options': 'nosniff' } })
})
`

  const denoJson = `{
  "tasks": {
    "start": "deno run --allow-net server.ts"
  }
}
`

  return [
    { path: 'server.ts', content: server },
    { path: 'deno.json', content: denoJson },
  ]
}

module.exports = { generate }
