'use strict'

function generate({ html = '', css = '', js = '', edgeFunctions = '', projectName = 'arc-app' }) {
  const assets = { '/': html }
  if (css) assets['/styles.css'] = css
  if (js) assets['/app.js'] = js

  const assetsEntries = Object.entries(assets)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n')

  const handlerNames = edgeFunctions
    ? [...new Set((edgeFunctions.match(/function (_handler_\w+)/g) ?? []).map(m => m.slice('function '.length)))]
    : []
  const handlerMapEntries = handlerNames.map(h => `  '${h.slice('_handler_'.length)}': ${h}`).join(',\n')

  const edgeFunctionsBlock = edgeFunctions
    ? `
// Edge functions (from @server declarations)
${edgeFunctions}

const _ARC_HANDLERS: Record<string, (req: Request) => Promise<Response>> = {
${handlerMapEntries}
}

async function handleEdgeFunction(path: string, req: Request): Promise<Response> {
  const segment = path.slice('/_arc/fn/'.length)
  if (segment.includes('/')) return new Response('Not Found', { status: 404 })
  const fn = _ARC_HANDLERS[segment]
  if (typeof fn !== 'function') return new Response('Edge function not found', { status: 404 })
  return await fn(req)
}
`
    : ''

  const edgeRoutingBlock = edgeFunctions
    ? `
    if (path.startsWith('/_arc/fn/')) {
      return await handleEdgeFunction(path, req)
    }
`
    : ''

  const server = `// Deno Deploy server — generated by Arc
// Deploy with: deployctl deploy --project=${projectName} server.ts
// Run locally: deno run --allow-net server.ts

import { serve } from "https://deno.land/std@0.208.0/http/server.ts"

const ASSETS: Record<string, string> = {
${assetsEntries}
}

function getContentType(path: string): string {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8'
  if (path.endsWith('.css')) return 'text/css'
  if (path.endsWith('.js')) return 'application/javascript'
  if (path.endsWith('.json')) return 'application/json'
  if (path.endsWith('.svg')) return 'image/svg+xml'
  if (path.endsWith('.png')) return 'image/png'
  if (path.endsWith('.ico')) return 'image/x-icon'
  return 'application/octet-stream'
}
${edgeFunctionsBlock}
serve(async (req: Request): Promise<Response> => {
  const url = new URL(req.url)
  let path = url.pathname
  if (path === '' || path === '/') path = '/'
${edgeRoutingBlock}
  const asset = ASSETS[path]
  if (asset !== undefined) {
    return new Response(asset, {
      headers: { 'Content-Type': getContentType(path) },
    })
  }

  return new Response('Not found', { status: 404 })
})
`

  const denoJson = `{
  "tasks": {
    "start": "deno run --allow-net server.ts"
  }
}
`

  return [
    { path: 'server.ts', content: server },
    { path: 'deno.json', content: denoJson },
  ]
}

module.exports = { generate }
