'use strict'

function generate({ html = '', css = '', js = '', edgeFunctions = '', projectName = 'arc-app' }) {
  const assets = { '/': html }
  if (css) assets['/styles.css'] = css
  if (js) assets['/app.js'] = js

  const assetsEntries = Object.entries(assets)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n')

  const edgeFunctionsBlock = edgeFunctions
    ? `
// Edge functions (from @server declarations)
${edgeFunctions}

async function handleEdgeFunction(path, req, res) {
  const segment = path.slice('/_arc/fn/'.length)
  if (segment.includes('/')) return false
  const fn = globalThis['_handler_' + segment]
  if (typeof fn !== 'function') return false
  try {
    const result = await fn(req)
    const status = result.status ?? 200
    const headers = {}
    if (result.headers) {
      for (const [k, v] of (result.headers.entries?.() ?? Object.entries(result.headers))) headers[k] = v
    }
    const body = result.body ? await result.arrayBuffer?.() ?? result.body : ''
    res.writeHead(status, headers)
    res.end(body)
  } catch (e) {
    res.writeHead(500, { 'Content-Type': 'application/json' })
    res.end(JSON.stringify({ error: 'Internal server error' }))
  }
  return true
}
`
    : ''

  const edgeRoutingBlock = edgeFunctions
    ? `
    if (urlPath.startsWith('/_arc/fn/')) {
      const handled = await handleEdgeFunction(urlPath, req, res)
      if (!handled) {
        res.writeHead(404)
        res.end('Edge function not found')
      }
      return
    }
`
    : ''

  const server = `// Node.js server — generated by Arc
// Run with: node server.js

const http = require('http')

const ASSETS = {
${assetsEntries}
}

function getContentType(path) {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8'
  if (path.endsWith('.css')) return 'text/css'
  if (path.endsWith('.js')) return 'application/javascript'
  if (path.endsWith('.json')) return 'application/json'
  if (path.endsWith('.svg')) return 'image/svg+xml'
  if (path.endsWith('.png')) return 'image/png'
  if (path.endsWith('.ico')) return 'image/x-icon'
  return 'application/octet-stream'
}
${edgeFunctionsBlock}
const server = http.createServer(async (req, res) => {
  let urlPath = (req.url || '/').split('?')[0]
  if (urlPath === '' || urlPath === '/') urlPath = '/'
${edgeRoutingBlock}
  const asset = ASSETS[urlPath]
  if (asset !== undefined) {
    res.writeHead(200, { 'Content-Type': getContentType(urlPath) })
    res.end(asset)
    return
  }

  res.writeHead(404)
  res.end('Not found')
})

const PORT = process.env.PORT ? parseInt(process.env.PORT) : 3000
server.listen(PORT, () => {
  console.log(\`arc: server running on http://localhost:\${PORT}\`)
})
`

  return [
    { path: 'server.js', content: server },
  ]
}

module.exports = { generate }
