'use strict'

const { resolveHandlerNames } = require('./deploy-utils')

function generate({ html = '', css = '', js = '', edgeFunctions = '', handlerNames = null }) {
  const assets = { '/': html }
  if (css) assets['/styles.css'] = css
  if (js) assets['/app.js'] = js

  const assetsEntries = Object.entries(assets)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n')

  const handlerMatches = resolveHandlerNames(handlerNames, edgeFunctions)

  const handlerMapEntries = handlerMatches
    .map(h => `  ${JSON.stringify(h.slice('_handler_'.length))}: ${h}`)
    .join(',\n')

  const edgeFunctionsBlock = edgeFunctions ? `
// Edge functions (from @server declarations)
${edgeFunctions}

// Explicit dispatch map (handlers are local fn declarations, not globals)
const _ARC_HANDLERS = Object.assign(Object.create(null), {
${handlerMapEntries}
})

// Wrap Node.js IncomingMessage as a Fetch API compatible request shim
async function _makeArcRequest(req) {
  const body = await new Promise((resolve, reject) => {
    const chunks = []
    let total = 0
    const timer = setTimeout(() => { req.destroy(); reject(new Error('body read timeout')) }, 30000)
    req.on('data', c => {
      total += c.length
      if (total > 1048576) { clearTimeout(timer); req.destroy(); reject(new Error('Request body too large')); return }
      chunks.push(c)
    })
    req.on('end', () => { clearTimeout(timer); resolve(Buffer.concat(chunks)) })
    req.on('error', e => { clearTimeout(timer); reject(e) })
  })
  const rawHeaders = req.headers
  return {
    method: req.method,
    url: 'http://localhost' + (req.url || '/'),
    headers: {
      get: (k) => rawHeaders[k.toLowerCase()] ?? null,
      has: (k) => k.toLowerCase() in rawHeaders,
    },
    arrayBuffer: () => Promise.resolve(body.buffer.slice(body.byteOffset, body.byteOffset + body.byteLength)),
    _arc_session: req._arc_session ?? {},
  }
}

async function handleEdgeFunction(urlPath, req, res) {
  const segment = urlPath.slice('/_arc/fn/'.length)
  if (segment.includes('/')) return false
  if (!Object.prototype.hasOwnProperty.call(_ARC_HANDLERS, segment)) return false
  const fn = _ARC_HANDLERS[segment]
  if (typeof fn !== 'function') return false
  try {
    const arcReq = await _makeArcRequest(req)
    const result = await fn(arcReq)
    const status = result.status ?? 200
    const headers = {}
    if (result.headers && typeof result.headers.entries === 'function') {
      for (const [k, v] of result.headers.entries()) headers[k] = v
    } else if (result.headers && typeof result.headers === 'object') {
      Object.assign(headers, result.headers)
    }
    let rawBody
    if (typeof result.arrayBuffer === 'function') {
      rawBody = Buffer.from(await result.arrayBuffer())
    } else {
      rawBody = Buffer.from(result.body ?? '')
    }
    if (rawBody.length > 10 * 1024 * 1024) {
      res.writeHead(500, { 'Content-Type': 'application/json' })
      res.end(JSON.stringify({ error: 'Response too large' }))
      return true
    }
    headers['X-Content-Type-Options'] = headers['X-Content-Type-Options'] ?? 'nosniff'
    headers['X-Frame-Options'] = headers['X-Frame-Options'] ?? 'SAMEORIGIN'
    headers['Content-Security-Policy'] = headers['Content-Security-Policy'] ?? "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; form-action 'self'"
    headers['Permissions-Policy'] = headers['Permissions-Policy'] ?? 'camera=(), microphone=(), geolocation=()'
    res.writeHead(status, headers)
    res.end(rawBody)
  } catch (e) {
    console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'edge_fn_error', msg: e instanceof Error ? e.message : String(e) }))
    res.writeHead(500, { 'Content-Type': 'application/json' })
    res.end(JSON.stringify({ error: 'Internal server error' }))
  }
  return true
}
` : ''

  const edgeRoutingBlock = edgeFunctions ? `
    if (urlPath.startsWith('/_arc/fn/')) {
      const handled = await handleEdgeFunction(urlPath, req, res)
      if (!handled) {
        res.writeHead(404, { 'Content-Type': 'text/plain', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'none'" })
        res.end('Edge function not found')
      }
      return
    }
` : ''

  const server = `// Node.js server: generated by Arc
// Run with: node server.js

const http = require('http')

const ASSETS = {
${assetsEntries}
}

function getContentType(path) {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8'
  if (path.endsWith('.css')) return 'text/css'
  if (path.endsWith('.js')) return 'application/javascript'
  if (path.endsWith('.json')) return 'application/json'
  if (path.endsWith('.svg')) return 'image/svg+xml'
  if (path.endsWith('.png')) return 'image/png'
  if (path.endsWith('.ico')) return 'image/x-icon'
  return 'application/octet-stream'
}
${edgeFunctionsBlock}
const server = http.createServer(async (req, res) => {
  let urlPath = (req.url || '/').split('?')[0]
  if (urlPath === '' || urlPath === '/') urlPath = '/'
  if (urlPath === '/_arc/health') {
    res.writeHead(200, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store, no-cache' })
    res.end(JSON.stringify({ status: 'ok', uptime: process.uptime(), ts: new Date().toISOString() }))
    return
  }
${edgeRoutingBlock}
  const asset = ASSETS[urlPath]
  if (asset !== undefined) {
    res.writeHead(200, {
      'Content-Type': getContentType(urlPath),
      'Content-Security-Policy': "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; form-action 'self'",
      'X-Content-Type-Options': 'nosniff',
      'X-Frame-Options': 'SAMEORIGIN',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
      'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
      'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
    })
    res.end(asset)
    return
  }

  res.writeHead(404, {
    'Content-Type': 'text/plain',
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'SAMEORIGIN',
    'Content-Security-Policy': "default-src 'none'",
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
  })
  res.end('Not found')
})

const _rawPort = process.env.PORT ? parseInt(process.env.PORT, 10) : 3000
const PORT = (Number.isInteger(_rawPort) && _rawPort > 0 && _rawPort < 65536) ? _rawPort : 3000
server.listen(PORT, () => {
  process.stdout.isTTY
    ? console.log(\`arc: server running on http://localhost:\${PORT}\`)
    : console.log(JSON.stringify({ ts: new Date().toISOString(), level: 'info', event: 'server_start', msg: \`arc: server running on http://localhost:\${PORT}\` }))
})
server.keepAliveTimeout = 65000
server.headersTimeout = 66000
server.requestTimeout = 300000
server.on('error', e => { console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'server_error', msg: e.message })); process.exit(1) })
server.on('clientError', (err, socket) => { console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'client_error', msg: err.message })); socket.end() })
process.on('SIGTERM', () => {
  console.log(JSON.stringify({ ts: new Date().toISOString(), level: 'info', event: 'server_shutdown_started' }))
  server.close(err => {
    if (err) console.error(JSON.stringify({ ts: new Date().toISOString(), level: 'error', event: 'server_shutdown_error', msg: err.message }))
    process.exit(err ? 1 : 0)
  })
})
`

  return [
    { path: 'server.js', content: server },
  ]
}

module.exports = { generate }
